batch service
ethersphere/bee pull request #1046
Opened 2020-12-11 12:09 UTC by acud

2 in 1 for better flexibility

2020-12-12 05:03 UTC, zelig commented on pkg/postage/events/events.go
> +type batchCreatedEvent struct {
```solidity
event BatchCreated(bytes32 indexed batchId, uint256 totalAmount, uint256 normalisedBalance, address owner, uint8 depth);

event BatchTopUp(bytes32 indexed batchId, uint256 topupAmount, uint256 normalisedBalance);

event BatchDepthIncrease(bytes32 indexed batchId, uint8 newDepth, uint256 normalisedBalance);

event PriceUpdate(uint256 price, uint256 totalOutPayment)
```

2020-12-12 05:03 UTC, zelig commented on pkg/postage/events/events.go
> +type batchCreatedEvent struct {
in. genergal all nornalisedBalance -> Value

2020-12-14 10:00 UTC, paxthemax requested changes
First pass review  of batch, focusing on events next.

Code looks good, clean, well organized. Minor points to consider addressing.

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/batch.go
> +	Owner []byte   // owner's ethereum address
Should we use `common.Address` from `go-ethereum` here?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/batch.go
> +	out := make([]byte, 93)
Should we declare some of these values as constants? Perhaps export them?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/batch.go
> +type Batch struct {
Consider adding an `Eq` function to compare?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/batch_test.go
> +	if !bytes.Equal(b.ID, a.ID) {
We could use an `Eq` function here, see above.

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/export_test.go
> +package batchstore
File is empty, consider removing?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/state.go
> +package batchstore
File is empty, consider removing?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/state_test.go
> +package batchstore_test
File is empty, consider removing?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +	mu    sync.Mutex          // mutex to lock statestore during atomic changes
Do we use a RWMutex here?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +func (s *Store) TopUp(id []byte, value *big.Int) error {
Do we need to lock on batch value changes?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +func (s *Store) UpdateDepth(id []byte, depth uint8) error {
See above?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +	buf := make([]byte, 9)
Does this need to be 8 or 9 bytes?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +	if len(totalBytes) > math.MaxUint8 {
This is to ensure that the value of total fits in an unit256, correct?

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store.go
> +	if totalLen > math.MaxUint8 {
Same as above

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store_test.go
> +func TestStore(t *testing.T) {
Empty test

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store_test.go
> +		t.Fatal("price not persisted")
Consider rewriting as `price: got %v, want %v`.

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store_test.go
> +		t.Fatal("value mismatch")
Consider rewriting as `value: got %v, want %v`.

2020-12-14 10:00 UTC, paxthemax commented on pkg/postage/batchstore/store_test.go
> +	newPrice := big.NewInt(99)
Perhaps a line of comment as to what we are trying to achieve here? As in: creating the store, changing the price, expecting different result.

2020-12-15 09:28 UTC, Eknir commented
Connected this issue with #928. @acud , lmk if this is good (or not)

2020-12-22 18:32 UTC, closed without merging