kademlia: return ErrNotFound on skip peers
ethersphere/bee pull request #1341
Opened 2021-02-25 14:08 UTC by acud

2021-02-26 09:20 UTC, zelig approved these changes

2021-02-27 11:36 UTC, zelig requested changes

2021-02-27 11:36 UTC, zelig commented on pkg/kademlia/kademlia.go
> +		switch l := len(skipPeers); l {
on second  thought this is not  a good idea. 
also disconnected peers etc clearly shows this should be an iterator function.
either way, checking  the length of skipPeers is a hack and not the right thing.
For instance if we had to prepopulate skipPeers with some nodes, which seems legit, suddenly, 
the closest node will not be found. 

Instead you need to check closest before you  check skippeers and  simply never return errwantself iff there is a closer peer even if it is to be skipped.

2021-03-01 10:01 UTC, closed without merging

2021-03-02 08:52 UTC, Eknir commented
Is this issue merged?