Storage incentives reservestate api
ethersphere/bee pull request #1586
Opened 2021-04-20 19:14 UTC by esadakar

2021-04-20 21:03 UTC, esadakar commented
![reservestate](https://user-images.githubusercontent.com/14264581/115463855-f0fc5580-a234-11eb-93c3-d28d383954db.png)

2021-04-21 03:57 UTC, zelig reviewed
consider adding a test?

2021-04-21 07:14 UTC, acud commented on pkg/postage/batchstore/store.go
> +func (s *store) GetReserveState() *postage.Reservestate {
bear in mind you're leaking the package internals here: `Outer` and `Inner` are pointers. It would be prudent to create a copy of them.

2021-04-21 07:15 UTC, acud approved these changes
+1 for a small test in `debugapi`

2021-04-21 10:46 UTC, acud commented on pkg/postage/batchstore/store.go
> +		Outer:     *s.rs.Outer,
`big.Int`s are meant to be passed as pointers, not as values, so it is needed to create a new `big.Int` and give it the value which is currently in the existing fields.
Also, there is a typo in the line below, where `Outer` is dereferenced as value for Inner

2021-04-21 10:47 UTC, acud commented on pkg/postage/reservestate.go
> +	Outer     big.Int `json:"outer"` // lower value limit for outer layer = the further half of chunks
`*big.Int`, for both

2021-04-21 10:47 UTC, acud requested changes
some comments relating to passing of `big.Int`s

2021-04-21 17:40 UTC, acud approved these changes

2021-04-21 17:41 UTC, acud commented on pkg/postage/reservestate.go
> +package postage
copyright missing here. otherwise LGTM

2021-04-21 17:41 UTC, acud commented on pkg/debugapi/postage_test.go
> +// Copyright 2020 The Swarm Authors. All rights reserved.
2021

2021-04-21 17:41 UTC, acud commented on pkg/debugapi/postage.go
> +// Copyright 2020 The Swarm Authors. All rights reserved.
21

2021-04-21 18:27 UTC, merged

2021-05-03 10:00 UTC, AuHau commented
Btw. @esadakar the new `GET /reservestate` endpoint is not documented in OpenAPI ;-)