postage stamps with indexes
ethersphere/bee pull request #1625
Opened 2021-04-29 22:31 UTC by zelig

this PR extends postage stamps with indexes
- indexes enable replacing stored chunks at the discretion of the owner: storer nodes store  only the latest chunk stamped with the same stamp (same batch same index)
- offer an easy way to catch overissuance as part of stamp validity check
- makes it possible to limit spoofing density proofs by mining chunks to a batch
- makes it possible to transfer ownership of arbitrary indexes 

the index is a 64-bit serialisation of
 - bucket depth (uint8, 1st byte, <24)
 - bucket index (neighbourhood index, uint32 <2^depth, bytes 2-4)
 - and the within-bucket index (uint32 <2^(batchdepth-bucketdepth), bytes 5-8)

2021-05-31 11:09 UTC, acud commented on pkg/postage/stampissuer.go
> +func bytesToIndex(buf []byte, depth uint8) (bucket, index uint32) {
depth not used, can be removed

2021-05-31 11:09 UTC, acud commented on pkg/postage/stampissuer.go
> +func indexToBytes(depth uint8, bucket, index uint32) []byte {
depth not used anywhere

2021-06-01 20:34 UTC, IxaBrjnko commented
Yay!! Thank you <3

2021-06-02 13:02 UTC, acud commented on pkg/localstore/mode_put.go
> +			return false, 0, err
err is `nil` here

2021-06-03 06:42 UTC, ralph-pichler commented
rebase on master, then change https://github.com/ethersphere/bee/blob/master/.github/workflows/beekeeper.yml#L16 to `0.2.0` to run integration tests with the new contract.

2021-06-03 12:05 UTC, esadakar commented
> rebase on master, then change https://github.com/ethersphere/bee/blob/master/.github/workflows/beekeeper.yml#L16 to `0.2.0` to run integration tests with the new contract.

Ok! Thanks.

2021-06-04 11:09 UTC, acud requested changes
> Reviewed 17 of 33 files at r1, 1 of 2 files at r2, 1 of 10 files at r4, 15 of 19 files at r7, 12 of 12 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: all files reviewed, 9 unresolved discussions (waiting on @esadakar and @zelig)

___
*[pkg/localstore/gc.go, line 184 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLc2TB2Po-AwepiaLt:-MbLc2TCEjV496TOGC3O:bsybmr3) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/gc.go#L184)):*
> ```Go
> 			return 0, false, err
> 		}
> 		err = db.postageIndexIndex.DeleteInBatch(batch, item)
> ```

need to add a test for the index, to see that the entry gets removed when GCing
___
*[pkg/localstore/localstore.go, line 511 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLcocd0SjP7nc02ak9:-MbLcoce3z6uwWGEkvmB:b-7ss83x) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/localstore.go#L511)):*
> ```Go
> 		},
> 		DecodeValue: func(keyItem shed.Item, value []byte) (e shed.Item, err error) {
> 			e = keyItem
> ```

this should not be here, there are other occurrences of this usage in this file and they should also be removed
___
*[pkg/localstore/mode_put_test.go, line 494 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLdnrs81YF9M0JuR7E:-MbLdnrs81YF9M0JuR7F:b4s7duw) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_put_test.go#L494)):*
> ```Go
> 	ts := time.Now().Unix()
> 
> 	modes := []storage.ModePut{storage.ModePutRequest, storage.ModePutRequestPin, storage.ModePutSync, storage.ModePutUpload, storage.ModePutUploadPin}
> ```

nit, this can be pulled out to a package-level variable
___
*[pkg/localstore/mode_set_test.go, line 113 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeZPAETj72vcEtQjl:-MbLeZPAETj72vcEtQjm:bkfnbsh) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L113)):*
> ```Go
> 				for _, ch := range chs {
> 					wantErr := leveldb.ErrNotFound
> 					_, err := db.retrievalDataIndex.Get(addressToItem(ch.Address()))
> ```

this is not needed since index counts are tested below
___
*[pkg/localstore/mode_set_test.go, line 119 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeVks4QKcFvosQ4FV:-MbLeVks4QKcFvosQ4FW:bkfnbsh) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L119)):*
> ```Go
> 
> 					// access index should not be set
> 					_, err = db.retrievalAccessIndex.Get(addressToItem(ch.Address()))
> ```

this is not needed since index counts are tested below
___
*[pkg/localstore/mode_set_test.go, line 131 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeRh96emwmjRyoPTo:-MbLeRh96emwmjRyoPTp:bylam5r) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L131)):*
> ```Go
> 
> 			for _, ch := range chs {
> 				newPullIndexTest(db, ch, 0, leveldb.ErrNotFound)(t)
> ```

this is not needed since we test this anyway below
___
*[pkg/postage/stamp.go, line 71 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLfI-7-SDxNnXePXna:-MbLfI-7-SDxNnXePXnb:bmewwxr) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/postage/stamp.go#L71)):*
> ```Go
> 
> // MarshalBinary gives the byte slice serialisation of a stamp:
> // batchID[32]|index[32]|SignatureUser[65]|SignatureOwner[65].
> ```

comment incorrect
___
*[pkg/postage/stamper.go, line 48 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLfjrEBz3MGOW2kYpk:-MbLfjrEBz3MGOW2kYpl:b-v8wdl4) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/postage/stamper.go#L48)):*
> ```Go
> 	toSign, err := toSignDigest(addr.Bytes(), st.issuer.batchID, index, ts)
> 	if err != nil {
> 		return nil, err
> ```

if there was an error here, we need to think about decrementing the issuer count
___
*[pkg/postage/listener/listener_test.go, line 41 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLgvedC0NcoTPve6s_:-MbLgveeD8bIKwUd8iTu:bb4pyn3) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/postage/listener/listener_test.go#L41)):*
> ```Go
> 			amount:           big.NewInt(42),
> 			normalisedAmount: big.NewInt(43),
> 			// bucketDepth:      10,
> ```

commented code can be removed


<!-- Sent from Reviewable.io -->

2021-06-04 11:32 UTC, esadakar reviewed
> Reviewed 1 of 33 files at r1, 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: 41 of 47 files reviewed, 9 unresolved discussions (waiting on @acud and @zelig)



<!-- Sent from Reviewable.io -->

2021-06-04 11:34 UTC, esadakar reviewed
> Reviewed 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: all files reviewed, 8 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/localstore/localstore.go, line 511 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLcocd0SjP7nc02ak9:-MbLn14MAj3FBuwKAu8-:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/localstore.go#L511)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this should not be here, there are other occurrences of this usage in this file and they should also be removed
</blockquote></details>

Done.
___
*[pkg/localstore/mode_put_test.go, line 494 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLdnrs81YF9M0JuR7E:-MbLn87r9Aleqy4Z7N1r:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_put_test.go#L494)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

nit, this can be pulled out to a package-level variable
</blockquote></details>

Done.
___
*[pkg/localstore/mode_set_test.go, line 113 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeZPAETj72vcEtQjl:-MbLnAqfBUdDBvn495zM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L113)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this is not needed since index counts are tested below
</blockquote></details>

Done.
___
*[pkg/localstore/mode_set_test.go, line 119 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeVks4QKcFvosQ4FV:-MbLn9su2j3W3Ahsn106:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L119)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this is not needed since index counts are tested below
</blockquote></details>

Done.
___
*[pkg/localstore/mode_set_test.go, line 131 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLeRh96emwmjRyoPTo:-MbLnCIl9ThXtmZeY8w2:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/localstore/mode_set_test.go#L131)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this is not needed since we test this anyway below
</blockquote></details>

Done.
___
*[pkg/postage/stamp.go, line 71 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLfI-7-SDxNnXePXna:-MbLnDPJ6zQt6_86rAtC:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/postage/stamp.go#L71)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

comment incorrect
</blockquote></details>

Done.
___
*[pkg/postage/listener/listener_test.go, line 41 at r9](https://reviewable.io/reviews/ethersphere/bee/1625#-MbLgvedC0NcoTPve6s_:-MbLnEaDAju2KeuyGVx6:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/62502f966b23993f66d3a4d73a1ce4e2910f2eb7/pkg/postage/listener/listener_test.go#L41)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

commented code can be removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 11:36 UTC, acud commented on pkg/postage/listener/listener_test.go
> +	// b, err := listener.PostageStampABI.Events["BatchCreated"].Inputs.NonIndexed().Pack(c.amount, c.normalisedAmount, common.BytesToAddress(c.owner), c.bucketDepth, c.depth, c.immutable)
needs to be removed

2021-06-04 14:16 UTC, acud approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r10, 1 of 3 files at r11, 2 of 2 files at r13, 1 of 1 files at r15, 3 of 3 files at r16, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625#-:-MbMNHrC3G07AiPZPP0U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zelig)



<!-- Sent from Reviewable.io -->

2021-06-07 08:16 UTC, zelig reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: all files reviewed, 4 unresolved discussions (waiting on @zelig)

___
*[pkg/postage/stamp.go, line 71 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbPYrPuDm0WJflFQTAV:-MbPYrPv7vkuLrTlV7R_:bn1tsj6) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stamp.go#L71)):*
> ```Go
> 
> // MarshalBinary gives the byte slice serialisation of a stamp:
> // batchID[32]|index[8]|Signature[65].
> ```

comment still missing timestamp field
___
*[pkg/postage/stamp_test.go, line 118 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbP_K5T04bUhNu0tGtm:-MbP_K5T04bUhNu0tGtn:b-beamqy) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stamp_test.go#L118)):*
> ```Go
> }
> 
> func newStamp(t *testing.T) *postage.Stamp {
> ```

is this not the same as under  postage/testing?
___
*[pkg/postage/stampissuer.go, line 68 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbPaUMH3e5YjBR-o-M4:-MbPaUMH3e5YjBR-o-M5:bktl70m) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stampissuer.go#L68)):*
> ```Go
> 
> // indexToBytes creates an uint64 index from
> // - bucket depth (uint8, 1st byte, <24)
> ```

this comment is outdated, the bucket depth itself is no longer part of this serialisation


<!-- Sent from Reviewable.io -->

2021-06-07 09:16 UTC, aloknerurkar approved these changes
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: all files reviewed, 4 unresolved discussions (waiting on @zelig)



<!-- Sent from Reviewable.io -->

2021-06-07 09:17 UTC, aloknerurkar reviewed
> Dismissed @zelig from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1625)* status: 47 of 50 files reviewed, 1 unresolved discussion (waiting on @acud, @esadakar, and @zelig)

___
*[pkg/postage/stamp.go, line 71 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbPYrPuDm0WJflFQTAV:-Mb_kkVT3vcCfbwLjmkD:bb6un1j) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stamp.go#L71)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

comment still missing timestamp field
</blockquote></details>

Done
___
*[pkg/postage/stamp_test.go, line 118 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbP_K5T04bUhNu0tGtm:-Mb_ke20AmICJSR0CGh-:b-896fjx) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stamp_test.go#L118)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

is this not the same as under  postage/testing?
</blockquote></details>

Done
___
*[pkg/postage/stampissuer.go, line 68 at r17](https://reviewable.io/reviews/ethersphere/bee/1625#-MbPaUMH3e5YjBR-o-M4:-Mb_kiUC0LJky_0LCoDD:bb6un1j) ([raw file](https://github.com/ethersphere/bee/blob/2231e985af85296c042229d57dc32fd59cc23ad8/pkg/postage/stampissuer.go#L68)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this comment is outdated, the bucket depth itself is no longer part of this serialisation
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-06-07 10:58 UTC, aloknerurkar approved these changes

2021-06-08 11:12 UTC, ralph-pichler commented
change 
* `GoerliPostageStampContractAddress` in `listener.go` to `0x621e455C4a139f5C4e4A8122Ce55Dc21630769E4`
* `GoerliStartBlock` to `4933174`

2021-06-09 11:00 UTC, esadakar commented
> change
> 
> * `GoerliPostageStampContractAddress` in `listener.go` to `0x621e455C4a139f5C4e4A8122Ce55Dc21630769E4`
> * `GoerliStartBlock` to `4933174`

Done!

2021-06-09 11:00 UTC, esadakar approved these changes

2021-06-11 08:13 UTC, merged