api,file: remove data length arg from pipeline builder
ethersphere/bee pull request #1671
Opened 2021-05-07 12:10 UTC by esadakar

2021-05-07 13:02 UTC, acud approved these changes
Looks great. Thanks for the improvement. PR description about why this was needed and what it improves would be nice :)

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671#-:-M_5uk9H0rKB0YJr_9OL:b-k1nnxf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar, @anatollupacescu, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-05-07 13:15 UTC, esadakar reviewed
Sure, added now.

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671#-:-M_5xoiODKYe_kQ3JDLi:b-53era2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar, @anatollupacescu, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-05-07 15:04 UTC, mrekucci requested changes
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671)* status: all files reviewed, 1 unresolved discussion (waiting on @aloknerurkar, @anatollupacescu, and @esadakar)

___
*[pkg/file/pipeline/builder/builder.go, line 80 at r1](https://reviewable.io/reviews/ethersphere/bee/1671#-M_6LMz7EeXoVNCjYki3:-M_6LMz7EeXoVNCjYki4:b-3hfw7p) ([raw file](https://github.com/ethersphere/bee/blob/9081cb0cedf6d4fc233ff91734791e2f13e82c47/pkg/file/pipeline/builder/builder.go#L80)):*
> ```Go
> 	for {
> 		c, err := r.Read(data)
> 		total += int64(c)
> ```

Please remove the `total` it isn't used.


<!-- Sent from Reviewable.io -->

2021-05-10 05:05 UTC, mrekucci approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671#-:-M_Jefkx6iikPGv-d9OR:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, and @anatollupacescu)



<!-- Sent from Reviewable.io -->

2021-05-10 06:25 UTC, aloknerurkar approved these changes
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)



<!-- Sent from Reviewable.io -->

2021-05-10 11:30 UTC, acud approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1671#-:-M_L1aUZ4Zs69_EH-WO5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)



<!-- Sent from Reviewable.io -->

2021-05-10 12:21 UTC, merged