feat(pushsync): add metrics to push flow
ethersphere/bee pull request #1691
Opened 2021-05-11 10:11 UTC by aloknerurkar

Following metrics are added:

- TotalSendAttempts
These are meant to see how many peers were considered for the push. We already track no. of successful pushes with `TotalSent`. So we should be able to infer how many failed in all with this.

- TotalFailedSendAttempts
This counter will count the no. of failed attempts. A failed attempt is when we actually made an attempt to send the data to the peer. This doesn't count the errors caused by accounting. However `TotalSendAttempts - (TotalSent + TotalFailedSendAttempts)` should tell us that.

- FailedCacheHits
This counter vector keeps track of failedRequestCache hits. It will use the `peer` and `chunk` labels to track traces for a {peer, chunk} send-request. We should ensure this no. does not rise to a high value.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1691)

2021-05-11 11:02 UTC, janos approved these changes
LGTM

2021-05-11 12:22 UTC, acud requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1691)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aloknerurkar and @zelig)

___
*[pkg/pushsync/metrics.go, line 76 at r1](https://reviewable.io/reviews/ethersphere/bee/1691#-M_QMwX-AAjOG3JMwFoB:-M_QMwX0BAH272m5DnLn:b-84awk) ([raw file](https://github.com/ethersphere/bee/blob/d02c08b7f505264f7e3da1fc44a9ef49624ab430/pkg/pushsync/metrics.go#L76)):*
> ```Go
> 				Help:      "FailedRequestCache hits",
> 			},
> 			[]string{"peer", "chunk"},
> ```

bear in mind that because you're logging every peer/chunk tuple with this metric, this might grow significantly in-memory. I am not sure what are in-memory eviction policy of prometheus metrics but this could become a problem at some point


<!-- Sent from Reviewable.io -->

2021-05-11 17:49 UTC, acud approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1691#-:-M_RXzPo71k_AZkJuEbq:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @zelig)



<!-- Sent from Reviewable.io -->

2021-05-12 05:40 UTC, merged

2021-05-12 21:31 UTC, ldeffenb commented
I can confirm that commit 0.6.0-0b0bb9e-dirty has these new pusher metrics.  However, the bee_pushsync_failed_cache_hits seem to keep incrementing after a chunk has failed enough times, even though no --verbosity 5 logs indicate that the chunk is still trying to push.

You can see my logs and the metrics section at:
https://pastebee.com/?b20ea4728cd82dbf89ef5f555f4e263c46855960141f81c3d49d2de6db22b9a6

I have the entire --verbosity 5 log for this node (which is still apparently trying to push that chunk) available.  Just ask me for bee6-5.out for my 0.6.0 node.

2021-05-13 17:31 UTC, ldeffenb commented
The failed-cache-hits metric is really going to swamp folks that are monitoring their nodes with prometheus.  I pushed a total of 5 files into the 0.6.0 test swarm and now have a bunch of chunks doing retries due to "stream reset".  But my /metrics has exploded!  See https://pastebee.com/?4c174c86dbf017a0b92420d681370d00f13235b8d0bb21feb3d7e816b5a85161 for a fragment.

2021-05-14 05:50 UTC, aloknerurkar commented
Hi @ldeffenb, Thanks for this information. 

The cache is an LRU bounded cache (1000 entries). Once we see an error from a peer for a chunk, we add him to the cache. However, he is not blocked yet. Once we see >3 errors from a peer, we will start skipping this peer during the push. As we would see more and more failures, new {peer, chunk} entries will be added and older ones will be evicted. This is the only way we unblock a {peer, chunk} request.

The moment we skip, we will add this metric. Ideally, we hoped we won't see too many errors all the time. This is why we did not think this will go out of hand. In a saturated topology, the retry logic should be able to find better peers and the request should ideally go through some other route. Not sure why we are seeing so many errors here in the first place.

```
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="539aba7d15e98814bb9e7803bfc1b87f32d0c19975074fdd7f9aa0f88891da27"} 20539
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="552136fedeaa5faff07a5b8b3ab16294a55b160af4d3e6984e37bf65736fdcc8"} 9041
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="8d42c2565b5948a8701f19e12aadec5a6b569dd6e2841ffa02ec3f339c349c6c"} 20545
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="8ec163755407cbae8a6fa56b48cf645009c86a6299d94a202d0e43b48fcb64fc"} 20543
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="905a6adfcc1a0c03e8b081ee9f126cdc8665a1e1bf71774d1014315bddcc7b29"} 20548
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="9342f1fb094d7b0839f5c1db87da6defe09e2eccf46e0b27faca0e5c83f6595a"} 11648
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="940f7248af27794516e6e57c81ce45799fb861aafbce7f48e2682ddf3191b5d4"} 20546
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="97f44eeb917a54fa85618842c696228e0057e54d8bc7a74ee572683c1dbef53f"} 20545
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="a1940b1df17c5a22396fd92b2658872addab1cfcd182a4e6f292b20019c0ba62"} 20542
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="a32d209ca3a1c235759cfb77dc13de38d6aa4051add4127ca9028e3ef4186f09"} 20540
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="a7b8de1cc181f098d029182339fb93600312ea9a81c4ccef13aad69a0b561952"} 20394
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="b2eec865af8505fb25a8ec95b829f2c98a6962bef0604010cdc132ee5aa1f007"} 20542
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="ca23e0fe44e27d3dd80bc4e26773cb0b89225ab1c183d1bc2f73dd41623790fa"} 20551
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="cf7adf1008662c70d525591f025e24cdfe17c9af7cbb7ecac8e840492d4bfb09"} 20550
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="e700b259d0e4072307f35afa705e51b2196dceeee6ae0ae71d26b167a5eb403a"} 20549
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="f84a9a81867bb09e4f634188ac5f2a4144d1625b8dea13c12302f76a1074b79c"} 20552
bee_pushsync_failed_cache_hits{chunk="d0748ab3ccc6513b1d31130b9fb6f26c02b11398c416d1c34c7317eb1282d9b5",peer="fd86d0d8589174175621a1dd82c2210c002ae9f9c39332e1e388560289b02321"} 20552
```

This is something we were hoping to catch with this metric. @acud can you comment on how we should proceed? I would still love to have this as this is the only way to diagnose the cache behavior.

2021-05-15 21:18 UTC, ldeffenb commented
The issue I see with this approach is that if the actual closest node for a given chunk is actually non-responsive, but well-connected and known within the neighborhood, then if I try to push that chunk, I will try to deliver it, get an error, go to the next closest who will try the closest (remember, it's a well connected neighborhood), so I'll get an error on that peer also for the same chunk, out to the 5 next closest peers putting 5 entries into this metric.

Remember, the metrics that I showed in this issue were from the very low activity 0.6.0 test swarm of only around 40 or so nodes.  If this was happening in the 0.5.3 public swarm with 100,000+ nodes, many of which seem to be running on overloaded hosts and are therefore bolluxing up a lot of destination spaces, and multiply that by many more chunks being introduced into the swarm, ... Well, I shudder to contemplate the size of this metric's value.