fix(libp2p,kademlia): fixes discrepency between kademlia and libp2p peers list
ethersphere/bee pull request #1696
Opened 2021-05-12 14:37 UTC by esadakar

Added extra checks in libp2p after connect calls to kademlia. This prevents peers that disconnect in the background while the stream handle is ongoing, from remining in the kademlia list

2021-05-12 15:04 UTC, anatollupacescu commented on pkg/p2p/libp2p/libp2p.go
> +		s.logger.Debugf("libp2p disconnect: peer %s not founds", overlay)
should this be in singular (found)?

2021-05-12 15:05 UTC, anatollupacescu approved these changes

2021-05-13 09:37 UTC, mrekucci approved these changes
Except the typo <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1696#-:-M__4YYmACxJaSlucBTl:b-wd8mi1)* status: all files reviewed, 1 unresolved discussion (waiting on @acud, @aloknerurkar, and @esadakar)



<!-- Sent from Reviewable.io -->

2021-05-13 18:54 UTC, acud requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1696)* status: all files reviewed, 6 unresolved discussions (waiting on @aloknerurkar, @esadakar, and @janos)

___
*[pkg/p2p/libp2p/libp2p.go, line 267 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZQb9I5Xrr9tfT1MIB:-M_ZQb9I5Xrr9tfT1MIC:b-2a09t5) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L267)):*
> ```Go
> 		overlay := i.BzzAddress.Overlay
> 
> 		if s.notifier == nil {
> ```

i think this can be removed. `notifier` is never `nil` while the node is running
___
*[pkg/p2p/libp2p/libp2p.go, line 363 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZQx-B4AUAXpMW4pkN:-M_ZQx-B4AUAXpMW4pkO:b-xa94x1) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L363)):*
> ```Go
> 		s.metrics.HandledStreamCount.Inc()
> 		if !s.peers.Exists(overlay) {
> 			s.logger.Debugf("libp2p: inbound peer %s does not exist, disconnecting", overlay)
> ```

isn't the prefix here supposed to be `stream handler`?
___
*[pkg/p2p/libp2p/libp2p.go, line 368 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZR0JvEdfmDW5DODeJ:-M_ZR0JvEdfmDW5DODeK:bb672f7) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L368)):*
> ```Go
> 		}
> 
> 		s.logger.Debugf("successfully connected to peer %s%s (inbound)", i.BzzAddress.ShortString(), i.LightString())
> ```

i would add the same prefix to these messages here too and double check all log lines printed in this function have it too
___
*[pkg/p2p/libp2p/libp2p.go, line 602 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZRMz-2rOLyM62cByQ:-M_ZRMz-2rOLyM62cByR:bljikg7) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L602)):*
> ```Go
> 				_ = s.Disconnect(overlay)
> 				s.protocolsmu.RUnlock()
> 				return nil, fmt.Errorf("connectOut: protocol %w", err)
> ```

consider: adding information about which protocol failed. the error is wrapped but the `protocol` in the message doesn't really say anything. more information will be availble from `tn`
___
*[pkg/p2p/libp2p/libp2p.go, line 609 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZRb2uBXTfP_JOYwYC:-M_ZRb2uBXTfP_JOYwYD:b-4eii79) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L609)):*
> ```Go
> 
> 	if !s.peers.Exists(overlay) {
> 		s.logger.Debugf("libp2p Connect: peer %s does not exist, disconnecting", overlay)
> ```

it is not necessary to log and return an error. you can decorate the returned error with more information when necessary and the calling context will log is as necessary


<!-- Sent from Reviewable.io -->

2021-05-14 07:56 UTC, esadakar reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1696)* status: all files reviewed, 7 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @esadakar, and @janos)

___
*[pkg/p2p/libp2p/libp2p.go, line 363 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZQx-B4AUAXpMW4pkN:-M_dqC-t1vF00OCGo0ML:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L363)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

isn't the prefix here supposed to be `stream handler`?
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 368 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZR0JvEdfmDW5DODeJ:-M_dqCGTBTwb5dF06GOM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L368)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

i would add the same prefix to these messages here too and double check all log lines printed in this function have it too
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 602 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZRMz-2rOLyM62cByQ:-M_dqs9hEK7gRPwqlcTD:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L602)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

consider: adding information about which protocol failed. the error is wrapped but the `protocol` in the message doesn't really say anything. more information will be availble from `tn`
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 609 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_dqzvh7NYJqIkswsLt:-M_dqzvh7NYJqIkswsLu:bobo09) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L609)):*
> ```
> s.logger.Debugf("libp2p Connect: peer %s does not exist
> ```
___
*[pkg/p2p/libp2p/libp2p.go, line 609 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZRb2uBXTfP_JOYwYC:-M_drp3U5jul0XefdRlB:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L609)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

it is not necessary to log and return an error. you can decorate the returned error with more information when necessary and the calling context will log is as necessary
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 650 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_W-nOCMpJLHLleSKr1-r1-650:-M_drq4B6yq04yrBnXFD:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L650)):*
<details><summary><i>Previously, anatollupacescu (Anatolie Lupacescu) wrote…</i></summary><blockquote>

should this be in singular (found)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-14 07:56 UTC, esadakar reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1696)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @janos, and @mrekucci)

___
*[pkg/p2p/libp2p/libp2p.go, line 267 at r1](https://reviewable.io/reviews/ethersphere/bee/1696#-M_ZQb9I5Xrr9tfT1MIB:-M_ds9dv3UbWO2Pduhid:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/06a8c00010df667dcf9fb6f083bce7ea9f6a4ee4/pkg/p2p/libp2p/libp2p.go#L267)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

i think this can be removed. `notifier` is never `nil` while the node is running
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-14 11:04 UTC, acud approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, @esadakar, and @janos)



<!-- Sent from Reviewable.io -->

2021-05-14 12:26 UTC, merged