refactor: rename db-capacity flag to cache-capacity
ethersphere/bee pull request #1704
Opened 2021-05-13 12:26 UTC by anatollupacescu

2021-05-13 18:52 UTC, acud approved these changes

2021-05-13 18:52 UTC, acud commented on packaging/bee.yaml
>  ## db capacity in chunks, multiply by 4096 to get approximate capacity in bytes
`db cache capacity`

2021-05-13 18:52 UTC, acud commented on packaging/homebrew/bee.yaml
>  ## db capacity in chunks, multiply by 4096 to get approximate capacity in bytes
same

2021-05-13 18:52 UTC, acud commented on packaging/scoop/bee.yaml
>  ## db capacity in chunks, multiply by 4096 to get approximate capacity in bytes
same

2021-05-14 06:08 UTC, aloknerurkar approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @anatollupacescu, @esadakar, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-05-14 07:06 UTC, zelig approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @anatollupacescu, @esadakar, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-05-14 07:44 UTC, mrekucci requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: all files reviewed, 4 unresolved discussions (waiting on @anatollupacescu and @esadakar)

___
*[cmd/bee/cmd/start.go, line 120 at r1](https://reviewable.io/reviews/ethersphere/bee/1704#-M_doALV9fIabPz9ZPQI:-M_doALV9fIabPz9ZPQJ:b-lzxj7g) ([raw file](https://github.com/ethersphere/bee/blob/995af63fd0cc1604ebbc94b8c70cc7df40d3c9f1/cmd/bee/cmd/start.go#L120)):*
> ```Go
> 			b, err := node.NewBee(c.config.GetString(optionNameP2PAddr), signerConfig.address, *signerConfig.publicKey, signerConfig.signer, c.config.GetUint64(optionNameNetworkID), logger, signerConfig.libp2pPrivateKey, signerConfig.pssPrivateKey, node.Options{
> 				DataDir:                  c.config.GetString(optionNameDataDir),
> 				DBCapacity:               c.config.GetUint64(optionNameDBCapacity),
> ```

You forgot to rename the `DBCapacity` option.


<!-- Sent from Reviewable.io -->

2021-05-14 08:13 UTC, esadakar approved these changes
Good to merge, after acud's requests.

2021-05-14 09:11 UTC, mrekucci approved these changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @anatollupacescu)



<!-- Sent from Reviewable.io -->

2021-05-14 09:13 UTC, anatollupacescu reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @acud)

___
*[packaging/bee.yaml, line 19 at r1](https://reviewable.io/reviews/ethersphere/bee/1704#-M__gH74WeCPugl21axk-r1-19:-M_e8XrABDG7YdOrbLo3:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/fa5b07e38e91753e87ba968b88f0137a9b956bd7/packaging/bee.yaml#L19)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`db cache capacity`
</blockquote></details>

Done.
___
*[packaging/homebrew/bee.yaml, line 19 at r1](https://reviewable.io/reviews/ethersphere/bee/1704#-M__gH74WeCPugl21axl-r1-19:-M_e8Yz37mEWBu_vUFLo:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/fa5b07e38e91753e87ba968b88f0137a9b956bd7/packaging/homebrew/bee.yaml#L19)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[packaging/scoop/bee.yaml, line 17 at r1](https://reviewable.io/reviews/ethersphere/bee/1704#-M__gH74WeCPugl21axm-r1-17:-M_e8Zeb-WyCdpp7DZq7:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/fa5b07e38e91753e87ba968b88f0137a9b956bd7/packaging/scoop/bee.yaml#L17)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-19 09:20 UTC, vandot commented on packaging/docker/env
>  # BEE_DB_CAPACITY=5000000
rename `BEE_DB_CAPACITY ` to `BEE_CACHE_CAPACITY`

2021-05-19 11:01 UTC, anatollupacescu reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1704)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @acud, @aloknerurkar, @mrekucci, @vandot, and @zelig)

___
*[packaging/docker/env, line 27 at r2](https://reviewable.io/reviews/ethersphere/bee/1704#-M_dxiE9P9Fw_1hGsdeJ-r2-27:-Ma3HOdf9qo2haYAbVID:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e2906a86c16177800f3d4415f8af8a56756545c5/packaging/docker/env#L27)):*
<details><summary><i>Previously, vandot (Ivan Vandot) wrote…</i></summary><blockquote>

rename `BEE_DB_CAPACITY ` to `BEE_CACHE_CAPACITY`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-19 12:01 UTC, merged