feat: bootnodes drop peers from oversaturated bins
ethersphere/bee pull request #1715
Opened 2021-05-14 14:06 UTC by esadakar

2021-05-14 16:24 UTC, acud requested changes
very nice. I have a few minor suggestions

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1715#-:-M_fgJjB-QuGLg_ojGTC:bi0hf2o)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @anatollupacescu, @esadakar, and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 780 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fe6_4AB9JOyHqpbXP:-M_fe6_4AB9JOyHqpbXQ:b-ysr79j) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L780)):*
> ```Go
> 
> 		if k.bootnode {
> 			if randPeer := k.randomPeer(po); !randPeer.IsZero() {
> ```

`randPeer` should never be zero. consider returning an error from `randomPeer` to control flow
___
*[pkg/topology/kademlia/kademlia.go, line 783 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fePwY6kon9XZyawUl:-M_fePwY6kon9XZyawUm:b-3kfm34) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L783)):*
> ```Go
> 				_ = k.p2p.Disconnect(randPeer)
> 			}
> 			return k.Announce(ctx, address)
> ```

I would continue execution to `k.connected`, otherwise the peer doesn't get added to the peers list. Also the select that triggers `manageC` should be executed
___
*[pkg/topology/kademlia/kademlia.go, line 1231 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fepZI4YLR0qxCbp6h:-M_fepZI4YLR0qxCbp6i:bdtyt4r) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L1231)):*
> ```Go
> 
> 	rndIndx, err := random.Int(random.Reader, big.NewInt(int64(len(peers))))
> 	if err != nil {
> ```

would be better to just return the error
___
*[pkg/topology/kademlia/kademlia_test.go, line 586 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_ffjpR-5TPX05givDn:-M_ffjpR-5TPX05givDo:b-7r4g7g) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L586)):*
> ```Go
> 		}
> 		// see depth is still as expected
> 		kDepth(t, kad, 5)
> ```

adding more peers outside of depth should not change the depth, so this check is redundant
___
*[pkg/topology/kademlia/kademlia_test.go, line 589 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fg6_D1YS5PwrZa8QK:-M_fg6_D1YS5PwrZa8QL:b-maz3m) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L589)):*
> ```Go
> 	}
> 
> 	if conns != -int32(depth*outSideDepthPeers) {
> ```

you might need to use `atomic` to get the value otherwise race detector might complain
___
*[pkg/topology/kademlia/kademlia_test.go, line 590 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fg03LD0XeDQEvmz20:-M_fg03LD0XeDQEvmz21:b-2i94wl) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L590)):*
> ```Go
> 
> 	if conns != -int32(depth*outSideDepthPeers) {
> 		t.Fatal("conns is not equal to the number of expected disconnected peers")
> ```

`...got %d want %d`


<!-- Sent from Reviewable.io -->

2021-05-14 17:30 UTC, esadakar reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1715)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @acud, @anatollupacescu, and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 780 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fe6_4AB9JOyHqpbXP:-M_fvHu9E-j1C4lJY82p:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L780)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`randPeer` should never be zero. consider returning an error from `randomPeer` to control flow
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia.go, line 783 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fePwY6kon9XZyawUl:-M_fvIcl4i7Z4AqYYjKj:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L783)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I would continue execution to `k.connected`, otherwise the peer doesn't get added to the peers list. Also the select that triggers `manageC` should be executed
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia.go, line 1231 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fepZI4YLR0qxCbp6h:-M_fvL-8834O-a-STPZe:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia.go#L1231)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

would be better to just return the error
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 586 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_ffjpR-5TPX05givDn:-M_fvLiO1mnWOnnkkR-k:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L586)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

adding more peers outside of depth should not change the depth, so this check is redundant
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 589 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fg6_D1YS5PwrZa8QK:-M_fvMa0CzIsRxsgKQei:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L589)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

you might need to use `atomic` to get the value otherwise race detector might complain
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 590 at r1](https://reviewable.io/reviews/ethersphere/bee/1715#-M_fg03LD0XeDQEvmz20:-M_fvN0858CBn43v9S0y:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/e712e7bc0a986ef180149505c71ad5e63c328899/pkg/topology/kademlia/kademlia_test.go#L590)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`...got %d want %d`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-15 06:54 UTC, acud approved these changes
great! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1715#-:-M_inVxV0P9ORQAbVLeH:b-7ayh2l)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-05-17 08:52 UTC, mrekucci approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1715#-:-M_tWbj73m-hXeR5tqLS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

___
*[pkg/topology/kademlia/kademlia.go, line 552 at r2](https://reviewable.io/reviews/ethersphere/bee/1715#-MZlBcZU7PycMACACTmQ:-MZlBcZU7PycMACACTmR:bq67fdn) ([raw file](https://github.com/ethersphere/bee/blob/e94d3fcfd6a642287e254d72a14e9e698ed48f3f/pkg/topology/kademlia/kademlia.go#L552)):*
> ```Go
> // when a bin is not saturated it means we would like to proactively
> // initiate connections to other peers in the bin.
> func binSaturated(oversaturationAmount int) binSaturationFunc {
> ```

I'd rename it from `oversaturationAmount` to `overSaturationAmount.


<!-- Sent from Reviewable.io -->

2021-05-17 10:01 UTC, anatollupacescu approved these changes

2021-05-17 15:22 UTC, merged