docs: document reupload
ethersphere/bee pull request #1755
Opened 2021-05-18 12:00 UTC by acud

adds the reupload functionality to the openapi spec

2021-05-18 12:28 UTC, anatollupacescu requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1755)* status: all files reviewed, 1 unresolved discussion (waiting on @acud)

___
*[openapi/Swarm.yaml, line 243 at r1](https://reviewable.io/reviews/ethersphere/bee/1755#-M_zRbm45CEyRYEwr1Kp:-M_zRbm45CEyRYEwr1Kq:b-kw6ckw) ([raw file](https://github.com/ethersphere/bee/blob/b6bc8659721562ef46485002ca8d08326cd47e49/openapi/Swarm.yaml#L243)):*
> ```YAML
>           description: Ok
>         "500":
>           $ref: "SwarmCommon.yaml#/components/responses/500"
> ```

what if the reference is not found, will it return 500?


<!-- Sent from Reviewable.io -->

2021-05-18 18:58 UTC, acud reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1755)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu)

___
*[openapi/Swarm.yaml, line 243 at r1](https://reviewable.io/reviews/ethersphere/bee/1755#-M_zRbm45CEyRYEwr1Kp:-Ma-pi5J7QDy2BXdmhLI:byvvotk) ([raw file](https://github.com/ethersphere/bee/blob/b6bc8659721562ef46485002ca8d08326cd47e49/openapi/Swarm.yaml#L243)):*
<details><summary><i>Previously, anatollupacescu (Anatolie Lupacescu) wrote…</i></summary><blockquote>

what if the reference is not found, will it return 500?
</blockquote></details>

for now yes, it will. since the reupload api is a bit more complex since it uses parallel uploads, it is a bit more tricky to break on a single not-found. that is why it is assumed that the node operator has all data before trying to reupload it (hopefully pinned)


<!-- Sent from Reviewable.io -->

2021-05-19 07:31 UTC, anatollupacescu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1755#-:-Ma2XLsiDmuwNrFu_jwN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)



<!-- Sent from Reviewable.io -->

2021-05-19 08:33 UTC, esadakar approved these changes

2021-05-19 08:34 UTC, merged