feat: Maintain originated balance
ethersphere/bee pull request #1870
Opened 2021-05-25 16:49 UTC by metacertain

This PR adds the following changes to accounting:
- When credit is done, if the originated argument is true, we deduct the price from the originated balance

- When settle (time based part) or debit decreases negative balance, originated balance is reduced towards zero along with the normal balance if the negative balance would become closer to zero.
- When notifyPaymentSent decreases negative balance, the value of the settlement is added to the originated balance, even increasing it's value above zero (as the payment was solely intended to move the originated balance). 

The PR also includes the use of originated parameter to credit in protocols

2021-05-25 19:32 UTC, zelig reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1870)* status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)

___
*[pkg/accounting/accounting.go, line 29 at r1](https://reviewable.io/reviews/ethersphere/bee/1870#-MaZwiiA56myntijaTZn:-MaZwiiB28zVRiqBd7VE:b-juatie) ([raw file](https://github.com/ethersphere/bee/blob/dafb2cb69827b71f4e063813e3b8e5d2992bcc99/pkg/accounting/accounting.go#L29)):*
> ```Go
> 	balancesPrefix           string    = "accounting_balance_"
> 	balancesSurplusPrefix    string    = "accounting_surplusbalance_"
> 	balancesOriginatedPrefix string    = "accounting_originatedbalance_"
> ```

the word originated is enigmatic. can we use a descriptive term?


<!-- Sent from Reviewable.io -->

2021-05-31 10:45 UTC, metacertain commented
> the word originated is enigmatic. can we use a descriptive term?
we concluded with @ralph-pichler this is a descriptive term, as this is the balance representing originated traffic.
however if there is a better suggestion, we can refactor

2021-06-02 05:44 UTC, zelig reviewed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1870)* status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)



<!-- Sent from Reviewable.io -->

2021-06-04 09:57 UTC, acud commented
@metacertain still not really clear to me what `originated` means in this sense here. there's no linked issue, no description of the term, i agree with viktor that this is just too obscure and not descriptive. can you please explain what it means?

2021-06-04 12:14 UTC, metacertain commented
> @metacertain still not really clear to me what `originated` means in this sense here. there's no linked issue, no description of the term, i agree with viktor that this is just too obscure and not descriptive. can you please explain what it means?

updated pr description with explanation of changes

2021-06-11 09:47 UTC, mrekucci requested changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1870)* status: all files reviewed, 5 unresolved discussions (waiting on @metacertain)

___
*[pkg/accounting/accounting.go, line 27 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuJuDpAvfy4PdZbivO:-MbuJuDpAvfy4PdZbivP:bqxuw5n) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L27)):*
> ```Go
> var (
> 	_                        Interface = (*Accounting)(nil)
> 	balancesPrefix           string    = "accounting_balance_"
> ```

The `string` type can be omitted (also for the vars below) and the related variables grouped.
___
*[pkg/accounting/accounting.go, line 275 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuMCaL2ZIN3oYYjmkO:-MbuMCaL2ZIN3oYYjmkP:b-v1ceha) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L275)):*
> ```Go
> 	//
> 
> 	if originated {
> ```

This can be rewritten in early return which would make the code more readable:
```golang
if !originated {
    return nil
}

...
```
___
*[pkg/accounting/accounting.go, line 277 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuMXFL-HFQRhODMxc4:-MbuMXFL-HFQRhODMxc5:b5ohpm3) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L277)):*
> ```Go
> 	if originated {
> 		originBalance, err := a.OriginatedBalance(peer)
> 		if err != nil {
> ```

No need for double `if`, just `if err != nil && !errors.Is(err, ErrPeerNoBalance)...` will do.
___
*[pkg/accounting/accounting.go, line 360 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuNPe15zmKtS4IrM2n:-MbuNPe2ApC9Awac34KY:b-c79epb) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L360)):*
> ```Go
> 		err = a.decreaseOriginatedBalanceTo(peer, oldBalance)
> 		if err != nil {
> 			a.logger.Warningf("settle: failed to decrease originated balance: %w", err)
> ```

The `%w` wouldn't work in this context, switch to `%v`
___
*[pkg/accounting/accounting.go, line 468 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuOAcj1CCkrWd_Q_uk:-MbuOAcj1CCkrWd_Q_ul:b-hixjgl) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L468)):*
> ```Go
> 
> func originatedBalanceKey(peer swarm.Address) string {
> 	return fmt.Sprintf("%s%s", balancesOriginatedPrefix, peer.String())
> ```

The `String()` method call on the `peer` is unnecessary  since `%s` formatting directive will do the same.
___
*[pkg/accounting/accounting.go, line 704 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuP0Iq8tHmRYanapUt:-MbuP0Iq8tHmRYanapUu:b-psv364) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L704)):*
> ```Go
> 	err = a.decreaseOriginatedBalanceBy(peer, amount)
> 	if err != nil {
> 		a.logger.Warningf("accounting: notifypaymentsent failed to decrease originated balance: %w", err)
> ```

As above, replace the `%w` with `%v`.
___
*[pkg/accounting/accounting.go, line 904 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuOg94B_PxDPDcL5AO:-MbuOg94B_PxDPDcL5AP:b-psv364) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L904)):*
> ```Go
> 	err = a.decreaseOriginatedBalanceTo(peer, nextBalance)
> 	if err != nil {
> 		a.logger.Warningf("increase balance: failed to decrease originated balance: %w", err)
> ```

As above, replace the `%w` with `%v`.
___
*[pkg/accounting/accounting.go, line 953 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuP5JqE4PLY-Ia7LNm:-MbuP5JqE4PLY-Ia7LNn:b-olbnp7) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L953)):*
> ```Go
> func (a *Accounting) decreaseOriginatedBalanceTo(peer swarm.Address, limit *big.Int) error {
> 
> 	zero := big.NewInt(0)
> ```

This is unnecessary since you've already declared the `zero` value above. 
___
*[pkg/accounting/accounting.go, line 958 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuPhFI-vjQsDLOFPaI:-MbuPhFI-vjQsDLOFPaJ:b-kentyf) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L958)):*
> ```Go
> 
> 	originatedBalance, err := a.OriginatedBalance(peer)
> 	if err != nil {
> ```

As above, this can be simplified into just one `if` statement.
___
*[pkg/accounting/accounting.go, line 984 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuPw4f6a8ppuRvtpJo:-MbuPw4f6a8ppuRvtpJp:b-kentyf) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/accounting.go#L984)):*
> ```Go
> 
> 	originatedBalance, err := a.OriginatedBalance(peer)
> 	if err != nil {
> ```

As above, this can be simplified into just one `if` statement.
___
*[pkg/accounting/metrics.go, line 43 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuQwD7AES6tS5qU2bh:-MbuQwD7AES6tS5qU2bi:bqjwhvo) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/metrics.go#L43)):*
> ```Go
> 			Help:      "Amount of BZZ credited to peers (potential cost of the node)",
> 		}),
> 		TotalOriginatedCreditedAmount: prometheus.NewCounter(prometheus.CounterOpts{
> ```

This can follow the position defined in the struct and so be moved to the penultimate place.
___
*[pkg/accounting/metrics.go, line 61 at r3](https://reviewable.io/reviews/ethersphere/bee/1870#-MbuRMlSEZSfbOnKP8tq:-MbuRMlSEZSfbOnKP8tr:b-lybnme) ([raw file](https://github.com/ethersphere/bee/blob/2d7d2131a23430edee3a8b4cf3e8ad1aedbe2817/pkg/accounting/metrics.go#L61)):*
> ```Go
> 			Help:      "Number of occurrences of BZZ credit events towards peers",
> 		}),
> 		OriginatedCreditEventsCount: prometheus.NewCounter(prometheus.CounterOpts{
> ```

This can follow the position defined in the struct and so be moved to the last place.


<!-- Sent from Reviewable.io -->

2021-06-11 11:30 UTC, metacertain commented
attended all comments as suggested, except

> The `String()` method call on the `peer` is unnecessary since `%s` formatting directive will do the same.

this lead to unexplained symptoms in the past, wouldn't try it at the moment

> > func (a *Accounting) decreaseOriginatedBalanceTo(peer swarm.Address, limit *big.Int) error {
> > 
> > 	zero := big.NewInt(0)
> > ```
> 
> This is unnecessary since you've already declared the `zero` value above.

we removed global zero as a risk factor, it could be changed by functions receiving it

2021-06-11 11:43 UTC, mrekucci approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1870#-:-Mbusdin0JlIEwd77o-A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)



<!-- Sent from Reviewable.io -->

2021-06-11 13:27 UTC, metacertain commented on pkg/accounting/accounting.go
> +	Credit(peer swarm.Address, price uint64, orignated bool) error
typo

2021-06-11 13:32 UTC, metacertain commented on pkg/accounting/accounting.go
> +	if nextBalance.Cmp(zero) > 0 {
if accounting balance is < 0
and originated balance is < accounting balance 
than originated balance = accounting balance

2021-06-11 13:48 UTC, acud approved these changes

2021-06-11 15:32 UTC, merged