feat: Negotiate cheques
ethersphere/bee pull request #1924
Opened 2021-05-31 02:27 UTC by metacertain

2021-05-31 05:55 UTC, zelig reviewed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1924)* status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)

___
*[pkg/settlement/swap/swapprotocol/swapprotocol.go, line 208 at r1](https://reviewable.io/reviews/ethersphere/bee/1924#-Mb-zCwL0aQyNBYEHOlO:-Mb-zCwM56SRUvhYqP78:b-25tpd5) ([raw file](https://github.com/ethersphere/bee/blob/c58e21dbf91740e8baefe0e264215d2aa574d96c/pkg/settlement/swap/swapprotocol/swapprotocol.go#L208)):*
> ```Go
> 	checkPeer := false
> 
> 	if checkPeer {
> ```

always false


<!-- Sent from Reviewable.io -->

2021-05-31 10:41 UTC, metacertain commented
> > Reviewed 7 of 7 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1924)_ status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)
> 
> _[pkg/settlement/swap/swapprotocol/swapprotocol.go, line 208 at r1](https://reviewable.io/reviews/ethersphere/bee/1924#-Mb-zCwL0aQyNBYEHOlO:-Mb-zCwM56SRUvhYqP78:b-25tpd5) ([raw file](https://github.com/ethersphere/bee/blob/c58e21dbf91740e8baefe0e264215d2aa574d96c/pkg/settlement/swap/swapprotocol/swapprotocol.go#L208)):_
> 
> > ```go
> > 	checkPeer := false
> > 
> > 	if checkPeer {
> > ```
> 
> always false

it is a work in progress, yet to introduce the component for registering whether a peer already had an initial deduction

2021-06-10 12:50 UTC, acud requested changes
> Reviewed 1 of 7 files at r1, 29 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1924)* status: 30 of 31 files reviewed, 15 unresolved discussions (waiting on @metacertain and @zelig)

___
*[.github/workflows/beekeeper.yml, line 17 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpn_Jt4nbZmP5rQYLX:-Mbpn_Jt4nbZmP5rQYLY:b-58so6z) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/.github/workflows/beekeeper.yml#L17)):*
> ```YAML
>       RUN_TYPE: "PR RUN"
>       SETUP_CONTRACT_IMAGE_TAG: "0.1.0"
>       BEEKEEPER_BRANCH: "thresholds"
> ```

needed?
___
*[pkg/accounting/accounting.go, line 32 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpoFGq9Ef2Pg3cxwkG:-MbpoFGr4j7qUI-UfEdL:bgn733f) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/accounting/accounting.go#L32)):*
> ```Go
> 	// this value is chosen so that tiny payments are prevented while still allowing small payments in environments with lower payment thresholds
> 	minimumPaymentDivisor    = int64(5)
> 	failedSettlementInterval = int64(10)
> ```

ten what? s/m/d/m/y? 
EDIT: seconds.
comment would be nice
___
*[pkg/accounting/accounting.go, line 333 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpoz980FATMorwmotf:-Mbpoz980FATMorwmotg:bvwdtwn) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/accounting/accounting.go#L333)):*
> ```Go
> 				// add settled amount to shadow reserve before sending it
> 				balance.shadowReservedBalance.Add(balance.shadowReservedBalance, paymentAmount)
> 				go a.payFunction(context.Background(), peer, paymentAmount)
> ```

there is no goroutine tracking here for shutdown, which means that payments made during shutdown might be lost
___
*[pkg/accounting/accounting_test.go, line 1100 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbppOlQCQUXOIEk06_H:-MbppOlQCQUXOIEk06_I:b7hxpzw) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/accounting/accounting_test.go#L1100)):*
> ```Go
> 	}
> 
> 	acc.Release(peer1Addr, 1)
> ```

is this needed at the end of the test?
___
*[pkg/settlement/swap/swap.go, line 101 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpqbzN55XxvC_Xauw9:-MbpqbzN55XxvC_XauwA:b-7zqllp) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/swap.go#L101)):*
> ```Go
> 
> 	if deduction.Cmp(big.NewInt(0)) > 0 {
> 		err = s.addressbook.AddDeductionFor(peer)
> ```

is this operation made under a peer lock? there might be a data race hiding here
___
*[pkg/settlement/swap/chequebook/chequestore_test.go, line 447 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbptyzy0Q4Z3xeacWsI:-Mbptyzz-ErlU44DrnYG:b-c2omw4) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/chequebook/chequestore_test.go#L447)):*
> ```Go
> 	sig := make([]byte, 65)
> 	chainID := int64(1)
> 	exchangeRate := big.NewInt(100)
> ```

can we have a short comment explaining the arithmetics and why the error should be returned?
___
*[pkg/settlement/swap/headers/utilities.go, line 24 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpuJYn7aLDN0J8jJaB:-MbpuJYn7aLDN0J8jJaC:b-wqil8) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/headers/utilities.go#L24)):*
> ```Go
> 	// ErrNoExchangeHeader denotes p2p.Header lacking specified field
> 	ErrNoExchangeHeader = errors.New("no exchange header")
> 	// ErrNoTargetHeader denotes p2p.Header lacking specified field
> ```

`ErrWrongComment`
___
*[pkg/settlement/swap/headers/utilities.go, line 45 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpuVKV1aC9osf5uzam:-MbpuVKV1aC9osf5uzan:bepfk84) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/headers/utilities.go#L45)):*
> ```Go
> 	deduction, err = ParseDeductionHeader(receivedHeaders)
> 	if err != nil {
> 		return exchangeRate, nil, err
> ```

Nit, but since the only error that can be returned from `ParseDeductionHeader` is `ErrNoDeductionHeader`, and since the calling contexts always fall back to deduction value `0`, then maybe it is not needed to return the error and just return a `0` from `ParseDeductionHeader`. However having it explicit as it is might be a nice option too, since it makes things a bit clearer in the calling contexts
___
*[pkg/settlement/swap/priceoracle/priceoracle.go, line 38 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpvzNIDA_Z58kkefhb:-MbpvzNJ7CEDYFYWLHr4:b-v7rqmh) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle.go#L38)):*
> ```Go
> type Service interface {
> 	io.Closer
> 	// Deposit starts depositing erc20 token into the chequebook. This returns once the transactions has been broadcast.
> ```

wrong comment, missing comments on other methods in the interface
___
*[pkg/settlement/swap/priceoracle/priceoracle.go, line 45 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpw4QK7h1AMilBVroJ:-Mbpw4QK7h1AMilBVroK:bsi76ij) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle.go#L45)):*
> ```Go
> 
> var (
> 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> ```

I think there's a `v0_2_0`
___
*[pkg/settlement/swap/priceoracle/priceoracle.go, line 81 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-MbpwrqW1Qq-QvPtOa9C:-MbpwrqW1Qq-QvPtOa9D:b-xbcvgc) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle.go#L81)):*
> ```Go
> 			ts := time.Now().Unix()
> 
> 			timeUntilNextPoll := time.Duration(s.timeDivisor-ts%s.timeDivisor) * time.Second
> ```

why not use a `const`?
___
*[pkg/settlement/swap/priceoracle/priceoracle.go, line 92 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpww-rERRu9lY3apZy:-Mbpww-rERRu9lY3apZz:b-ql0r4i) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle.go#L92)):*
> ```Go
> }
> 
> func (s *service) GetPrice(ctx context.Context) (*big.Int, *big.Int, error) {
> ```

since this wrapping method does not provide any further functionality, it can be removed and instead the unexported one can be exported
___
*[pkg/settlement/swap/priceoracle/priceoracle_test.go, line 22 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpx_rE1GEn4wJNKGFz:-Mbpx_rE1GEn4wJNKGG-:b-yveou2) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle_test.go#L22)):*
> ```Go
> 
> var (
> 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> ```

here too, v2?
___
*[pkg/settlement/swap/swapprotocol/swapprotocol_test.go, line 31 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpxu09DxpwiLUWaKAh:-Mbpxu09DxpwiLUWaKAi:bguvgc7) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/swapprotocol/swapprotocol_test.go#L31)):*
> ```Go
> )
> 
> func TestInit(t *testing.T) {
> ```

it would be good to document these tests also with a godoc style comment and also inline comments within the tests as they are not self describing and I find them hard to review


<!-- Sent from Reviewable.io -->

2021-06-10 14:02 UTC, ralph-pichler commented
___
*[pkg/settlement/swap/priceoracle/priceoracle.go, line 45 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpw4QK7h1AMilBVroJ:-MbqDdg368X5UNuzkrXK:bxkv7p4) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/settlement/swap/priceoracle/priceoracle.go#L45)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I think there's a `v0_2_0`
</blockquote></details>

that's a different price oracle, for this one there is only one version.


<!-- Sent from Reviewable.io -->

2021-06-10 14:28 UTC, metacertain commented
> >       BEEKEEPER_BRANCH: "thresholds"
> > ```
> 
> needed?

yes, this reduces thresholds by the magnitude of the newly introduced exchange rates
the beekeeper PR containing this should be merged at the same time as this to avoid breaks

> > 	failedSettlementInterval = int64(10)
> > ```
> 
> ten what? s/m/d/m/y?
> EDIT: seconds.

seconds indeed, added comment

> _[pkg/accounting/accounting.go, line 333 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpoz980FATMorwmotf:-Mbpoz980FATMorwmotg:bvwdtwn) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/accounting/accounting.go#L333)):_
> 
> > ```go
> > 				// add settled amount to shadow reserve before sending it
> > 				balance.shadowReservedBalance.Add(balance.shadowReservedBalance, paymentAmount)
> > 				go a.payFunction(context.Background(), peer, paymentAmount)
> > ```
> 
> there is no goroutine tracking here for shutdown, which means that payments made during shutdown might be lost

still to be fixed

> > 	acc.Release(peer1Addr, 1)
> > ```
> 
> is this needed at the end of the test?

we always do it consistently, not strictly needed

> > 		err = s.addressbook.AddDeductionFor(peer)
> > ```
> 
> is this operation made under a peer lock? there might be a data race hiding here

no need for lock in this case. this adds an empty struct to the specified address-index
if it is overwritten by another empty struct, wouldn't cause a problem
this is to remember deduction happened once towards a specific peer.
only one payment is ongoing at a time so no other payment is attempted without this saved yet

> > 	exchangeRate := big.NewInt(100)
> > ```
> 
> can we have a short comment explaining the arithmetics and why the error should be returned?

added comment to test
 
> `ErrWrongComment`

:)
 
> 
> Nit, but since the only error that can be returned from `ParseDeductionHeader` is `ErrNoDeductionHeader`, and since the calling contexts always fall back to deduction value `0`, then maybe it is not needed to return the error and just return a `0` from `ParseDeductionHeader`. However having it explicit as it is might be a nice option too, since it makes things a bit clearer in the calling contexts

this should be fine the way it is, than?
 
> > 	// Deposit starts depositing erc20 token into the chequebook. This returns once the transactions has been broadcast.
> > ```
> 
> wrong comment, missing comments on other methods in the interface

changed comment

 
> > var (
> > 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> > ```
> 
> I think there's a `v0_2_0`

thats the other ABI for postage stamps, v0_1_0 is good

> > 			timeUntilNextPoll := time.Duration(s.timeDivisor-ts%s.timeDivisor) * time.Second
> > ```
> 
> why not use a `const`?

added comment explaining logic
 
> > func (s *service) GetPrice(ctx context.Context) (*big.Int, *big.Int, error) {
> > ```
> 
> since this wrapping method does not provide any further functionality, it can be removed and instead the unexported one can be exported

done
 
> > 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> > ```
> 
> here too, v2?

v1 is ok

> > func TestInit(t *testing.T) {
> > ```
> 
> it would be good to document these tests also with a godoc style comment and also inline comments within the tests as they are not self describing and I find them hard to review

added comments

2021-06-11 11:30 UTC, acud approved these changes
LGTM abel. Thanks. :+1: 

> Reviewed 2 of 2 files at r3, 4 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1924#-:-MbupF-V-gziUQ0I8LaT:brwroh3)* status: all files reviewed, 1 unresolved discussion (waiting on @zelig)

___
*[pkg/accounting/accounting.go, line 333 at r2](https://reviewable.io/reviews/ethersphere/bee/1924#-Mbpoz980FATMorwmotf:-MbuoqNa3c99mTk0RqFs:b-idflxc) ([raw file](https://github.com/ethersphere/bee/blob/6281c66051a3646047337747f5c06d651041d7b6/pkg/accounting/accounting.go#L333)):*
<details><summary><i>Previously, metacertain wrote…</i></summary><blockquote>

> > ```go
> > 				// add settled amount to shadow reserve before sending it
> > 				balance.shadowReservedBalance.Add(balance.shadowReservedBalance, paymentAmount)
> > 				go a.payFunction(context.Background(), peer, paymentAmount)
> > ```
> > 

> 
> there is no goroutine tracking here for shutdown, which means that payments made during shutdown might be lost
> 

still to be fixed


> > 	acc.Release(peer1Addr, 1)
> > ```
> > 

> 
> is this needed at the end of the test?
> 

we always do it consistently, not strictly needed


> > 		err = s.addressbook.AddDeductionFor(peer)
> > ```
> > 

> 
> is this operation made under a peer lock? there might be a data race hiding here
> 

no need for lock in this case. this adds an empty struct to the specified address-index
if it is overwritten by another empty struct, wouldn't cause a problem
this is to remember deduction happened once towards a specific peer.
only one payment is ongoing at a time so no other payment is attempted without this saved yet


> > 	exchangeRate := big.NewInt(100)
> > ```
> > 

> 
> can we have a short comment explaining the arithmetics and why the error should be returned?
> 

added comment to test
 


> `ErrWrongComment`
> 

:)
 


> 
> Nit, but since the only error that can be returned from `ParseDeductionHeader` is `ErrNoDeductionHeader`, and since the calling contexts always fall back to deduction value `0`, then maybe it is not needed to return the error and just return a `0` from `ParseDeductionHeader`. However having it explicit as it is might be a nice option too, since it makes things a bit clearer in the calling contexts
> 

this should be fine the way it is, than?
 


> > 	// Deposit starts depositing erc20 token into the chequebook. This returns once the transactions has been broadcast.
> > ```
> > 

> 
> wrong comment, missing comments on other methods in the interface
> 

changed comment

 


> > var (
> > 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> > ```
> > 

> 
> I think there's a `v0_2_0`
> 

thats the other ABI for postage stamps, v0_1_0 is good


> > 			timeUntilNextPoll := time.Duration(s.timeDivisor-ts%s.timeDivisor) * time.Second
> > ```
> > 

> 
> why not use a `const`?
> 

added comment explaining logic
 


> > func (s *service) GetPrice(ctx context.Context) (*big.Int, *big.Int, error) {
> > ```
> > 

> 
> since this wrapping method does not provide any further functionality, it can be removed and instead the unexported one can be exported
> 

done
 


> > 	priceOracleABI = transaction.ParseABIUnchecked(priceoracleabi.PriceOracleABIv0_1_0)
> > ```
> > 

> 
> here too, v2?
> 

v1 is ok


> > func TestInit(t *testing.T) {
> > ```
> > 

> 
> it would be good to document these tests also with a godoc style comment and also inline comments within the tests as they are not self describing and I find them hard to review
> 

added comments

</blockquote></details>

thanks. 


<!-- Sent from Reviewable.io -->

2021-06-11 18:38 UTC, merged

2021-06-11 19:07 UTC, ldeffenb commented
Is this a breaking change due to the new protocol streams?  In other words, if I update to the current master, can I still participate in the 0.6.2 swarm?