feat(lightnode): add prometheus metrics
ethersphere/bee pull request #1979
Opened 2021-06-03 13:38 UTC by mrekucci

Adds the following metrics:
- number of currently connected peers
- number of currently disconnected peers

2021-06-03 18:45 UTC, acud requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1979)* status: all files reviewed, 1 unresolved discussion (waiting on @aloknerurkar, @anatollupacescu, and @mrekucci)

___
*[pkg/topology/lightnode/container.go, line 63 at r1](https://reviewable.io/reviews/ethersphere/bee/1979#-MbIBIzB5z3Mw6qBbQSm:-MbIBIzB5z3Mw6qBbQSn:bjigxy5) ([raw file](https://github.com/ethersphere/bee/blob/eb7f40e991e3ff334b868a44b5db881ae1b31713/pkg/topology/lightnode/container.go#L63)):*
> ```Go
> 
> func (c *Container) KickOut(_ p2p.Peer) {
> 	c.metrics.TotalKickedPeers.Inc()
> ```

this metric can be inside `libp2p`, it doesn't really matter to have it on the light node container. also, if the peer info is not used, why do we need it?


<!-- Sent from Reviewable.io -->

2021-06-04 07:28 UTC, mrekucci reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1979)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @acud, @aloknerurkar, and @anatollupacescu)

___
*[pkg/topology/lightnode/container.go, line 63 at r1](https://reviewable.io/reviews/ethersphere/bee/1979#-MbIBIzB5z3Mw6qBbQSm:-MbKuynV6As6bYS7VhXM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/eb7f40e991e3ff334b868a44b5db881ae1b31713/pkg/topology/lightnode/container.go#L63)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this metric can be inside `libp2p`, it doesn't really matter to have it on the light node container. also, if the peer info is not used, why do we need it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 07:51 UTC, anatollupacescu approved these changes

2021-06-04 08:53 UTC, acud approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1979#-:-MbLDb7o-FQXQYVGf3KJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar)



<!-- Sent from Reviewable.io -->

2021-06-04 09:27 UTC, merged