fix: api errors related to postage stamps
ethersphere/bee pull request #2037
Opened 2021-06-09 13:24 UTC by aloknerurkar

This PR attempts to solve #2026 in part.

This particular change tries to address the postage bucket full error which is annoying as the user does not understand that he cannot use the batch anymore.

We can create a separate `errors.go` file in `pkg/api` which could house all these error case handlers. This way we can edit the same file from time to time to add special case handling.

@acud @agazso @AuHau @Eknir

2021-06-09 15:11 UTC, agazso commented
Sending PSS message with the postage bucket full may lead to similar issue (see #1988). 

@aloknerurkar do you plan to address that in this PR as well?

2021-06-10 05:59 UTC, zelig approved these changes
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @AuHau, and @Eknir)



<!-- Sent from Reviewable.io -->

2021-06-10 08:51 UTC, mrekucci requested changes
Since the `jsonhttp.PaymentRequired` returns `402`, all the affected endpoint definitions in `openapi/Swarm.yaml` should be also adjusted accordingly.

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037#-:-Mbp5XTHAc67jAP5qVOb:bw6heei)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @AuHau, and @Eknir)



<!-- Sent from Reviewable.io -->

2021-06-10 09:01 UTC, acud requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037)* status: all files reviewed, 1 unresolved discussion (waiting on @aloknerurkar, @AuHau, and @Eknir)

___
*[pkg/api/bzz.go, line 36 at r2](https://reviewable.io/reviews/ethersphere/bee/2037#-Mbp8atj6Rm4XvNNiK_n:-Mbp8atk-OohNizzQs4w:b25qoqf) ([raw file](https://github.com/ethersphere/bee/blob/217e55810647b4d9623c767fb5f0fff565ec198c/pkg/api/bzz.go#L36)):*
> ```Go
> )
> 
> func mappedHTTPErr(w http.ResponseWriter, e error, defaultMsg interface{}) {
> ```

i think that having such a pattern would be useful if all middlewares would just return an error to an upper layer middleware that would then translate the actual errors into a response. but since we don't do this I would vote for explicitly handling the errors within the handlers


<!-- Sent from Reviewable.io -->

2021-06-10 10:12 UTC, aloknerurkar commented
___
*[pkg/api/bzz.go, line 36 at r2](https://reviewable.io/reviews/ethersphere/bee/2037#-Mbp8atj6Rm4XvNNiK_n:-MbpP7lDE8jdrpjaQZGE:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/217e55810647b4d9623c767fb5f0fff565ec198c/pkg/api/bzz.go#L36)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

i think that having such a pattern would be useful if all middlewares would just return an error to an upper layer middleware that would then translate the actual errors into a response. but since we don't do this I would vote for explicitly handling the errors within the handlers
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-10 10:12 UTC, aloknerurkar reviewed
> Dismissed @acud from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @acud, @AuHau, @Eknir, and @zelig)



<!-- Sent from Reviewable.io -->

2021-06-10 10:42 UTC, acud approved these changes
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AuHau, @Eknir, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-06-10 10:42 UTC, acud approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037#-:-MbpW4dF8BiQnLw8bMDf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AuHau, @Eknir, and @mrekucci)



<!-- Sent from Reviewable.io -->

2021-06-10 10:55 UTC, mrekucci approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2037#-:-MbpYyL74M1snKa4RrNL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AuHau and @Eknir)



<!-- Sent from Reviewable.io -->

2021-06-10 11:11 UTC, merged