fix: set explicit gas limits
ethersphere/bee pull request #2101
Opened 2021-06-15 14:24 UTC by ralph-pichler

2021-06-15 19:23 UTC, zelig requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2101)* status: all files reviewed, 1 unresolved discussion (waiting on @ralph-pichler)

___
*[pkg/postage/postagecontract/contract.go, line 75 at r1](https://reviewable.io/reviews/ethersphere/bee/2101#-McG7-ap50Tsag3YYjZq:-McG7-ap50Tsag3YYjZr:bto8f3v) ([raw file](https://github.com/ethersphere/bee/blob/95e2451d434bb7da01af4bfd47b2b251820b326f/pkg/postage/postagecontract/contract.go#L75)):*
> ```Go
> 		Data:     callData,
> 		GasPrice: sctx.GetGasPrice(ctx),
> 		GasLimit: 65000,
> ```

should this not depend on the chain you use?


<!-- Sent from Reviewable.io -->

2021-06-15 19:23 UTC, zelig approved these changes
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2101)* status: all files reviewed, 1 unresolved discussion (waiting on @ralph-pichler)

___
*[pkg/postage/postagecontract/contract.go, line 75 at r1](https://reviewable.io/reviews/ethersphere/bee/2101#-McG7-ap50Tsag3YYjZq:-McG7GOODZkrM_eGthpQ:bx46w1t) ([raw file](https://github.com/ethersphere/bee/blob/95e2451d434bb7da01af4bfd47b2b251820b326f/pkg/postage/postagecontract/contract.go#L75)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

should this not depend on the chain you use?
</blockquote></details>

same for all values.


<!-- Sent from Reviewable.io -->

2021-06-15 21:34 UTC, metacertain approved these changes

2021-06-16 06:26 UTC, ralph-pichler reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2101)* status: all files reviewed, 1 unresolved discussion (waiting on @zelig)

___
*[pkg/postage/postagecontract/contract.go, line 75 at r1](https://reviewable.io/reviews/ethersphere/bee/2101#-McG7-ap50Tsag3YYjZq:-McITmZH5m6mLUgQOwRF:by2m3wo) ([raw file](https://github.com/ethersphere/bee/blob/95e2451d434bb7da01af4bfd47b2b251820b326f/pkg/postage/postagecontract/contract.go#L75)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

same for all values.
</blockquote></details>

no, the gas usage should be similar on any chain (provided the evm version is the same which seems a reasonable assumption). the primary potential issue is a future hardfork with big gas changes, but there is nothing we can do about that now (except using the estimator which we cannot do on xdai/nethermind).


<!-- Sent from Reviewable.io -->

2021-06-16 08:20 UTC, merged