fix: use raw block hash
ethersphere/bee pull request #2454
Opened 2021-08-30 09:18 UTC by ralph-pichler

2021-09-30 12:45 UTC, notanatol approved these changes

2021-11-05 22:32 UTC, zelig approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)



<!-- Sent from Reviewable.io -->

2021-11-08 08:19 UTC, mrekucci approved these changes

2021-11-25 12:40 UTC, acud requested changes
blocking this just in case, so that it doesn't get merged by accident, at least for now

2022-01-23 01:45 UTC, closed without merging