fix: replace readAll with limited readers
ethersphere/bee pull request #2460
Opened 2021-08-31 12:15 UTC by notanatol

2021-08-31 13:39 UTC, mrekucci reviewed
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @notanatol)

___
*[pkg/api/chunk.go, line 90 at r2](https://reviewable.io/reviews/ethersphere/bee/2460#-MiRQ_u4AIEGn7K7czgc:-MiRQ_u4AIEGn7K7czgd:bdof0an) ([raw file](https://github.com/ethersphere/bee/blob/1cde0eb83f4b1c8f3162a0e1a8d36f689cc3e135/pkg/api/chunk.go#L90)):*
> ```Go
> 	}
> 
> 	reader := io.LimitReader(r.Body, swarm.ChunkSize+swarm.SpanSize)
> ```

Nice optimization. I'd suggest to use `io.ReadFull(r.Body, payload)`with an allocated buffer `payload := make([]byte, swarm.ChunkSize+swarm.SpanSize)` instead.
___
*[pkg/api/soc.go, line 61 at r2](https://reviewable.io/reviews/ethersphere/bee/2460#-MiRQL-WDFeJE-pR34Ns:-MiRQL-WDFeJE-pR34Nt:b-17qjie) ([raw file](https://github.com/ethersphere/bee/blob/1cde0eb83f4b1c8f3162a0e1a8d36f689cc3e135/pkg/api/soc.go#L61)):*
> ```Go
> 	}
> 
> 	reader := io.LimitReader(r.Body, swarm.ChunkSize+swarm.SpanSize)
> ```

Same here, I'd consider using `io.ReadFull(r.Body, payload)`with an allocated buffer `payload := make([]byte, swarm.ChunkSize+swarm.SpanSize)` instead.


<!-- Sent from Reviewable.io -->

2021-09-01 05:17 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @acud and @notanatol)

___
*[pkg/api/chunk.go, line 90 at r2](https://reviewable.io/reviews/ethersphere/bee/2460#-MiRQ_u4AIEGn7K7czgc:-MiUmA8N9tW2wKOSvlv1:btbsn79) ([raw file](https://github.com/ethersphere/bee/blob/1cde0eb83f4b1c8f3162a0e1a8d36f689cc3e135/pkg/api/chunk.go#L90)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

Nice optimization. I'd suggest to use `io.ReadFull(r.Body, payload)`with an allocated buffer `payload := make([]byte, swarm.ChunkSize+swarm.SpanSize)` instead.
</blockquote></details>

good point, but I wander if in our case we want to allow for reading of "less than" the size of the buffer.

`io.ReadAll` will return an error if fewer bytes were read - @acud would this behaviour fit here? 


<!-- Sent from Reviewable.io -->

2021-09-01 13:00 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2460)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @acud)

___
*[pkg/api/chunk.go, line 90 at r2](https://reviewable.io/reviews/ethersphere/bee/2460#-MiRQ_u4AIEGn7K7czgc:-MiWRJFe7Q9ZH_fznkJX:bwdyqcl) ([raw file](https://github.com/ethersphere/bee/blob/1cde0eb83f4b1c8f3162a0e1a8d36f689cc3e135/pkg/api/chunk.go#L90)):*
<details><summary><i>Previously, notanatol (Anatol) wrote…</i></summary><blockquote>

good point, but I wander if in our case we want to allow for reading of "less than" the size of the buffer.

`io.ReadAll` will return an error if fewer bytes were read - @acud would this behaviour fit here? 
</blockquote></details>

*correction: I meant that `io.ReadFull` will error if the payload is smaller than allocated buffer.


<!-- Sent from Reviewable.io -->

2021-09-01 15:16 UTC, acud requested changes
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2460)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @mrekucci and @notanatol)

___
*[pkg/api/chunk.go, line 90 at r2](https://reviewable.io/reviews/ethersphere/bee/2460#-MiRQ_u4AIEGn7K7czgc:-MiWvG5T4mRE34w4oUbO:b-68n06q) ([raw file](https://github.com/ethersphere/bee/blob/1cde0eb83f4b1c8f3162a0e1a8d36f689cc3e135/pkg/api/chunk.go#L90)):*
<details><summary><i>Previously, notanatol (Anatol) wrote…</i></summary><blockquote>

*correction: I meant that `io.ReadFull` will error if the payload is smaller than allocated buffer.
</blockquote></details>

we need to support reading of less than a full chunk definitely
___
*[pkg/api/pss.go, line 75 at r3](https://reviewable.io/reviews/ethersphere/bee/2460#-MiWvVqYBGXIJAzStSUm:-MiWvVqYBGXIJAzStSUn:b4dfeov) ([raw file](https://github.com/ethersphere/bee/blob/c2a7a6bd759671652a7cb30773a6530e80fc5a17/pkg/api/pss.go#L75)):*
> ```Go
> 	}
> 
> 	reader := io.LimitReader(r.Body, swarm.ChunkSize+swarm.SpanSize)
> ```

since there's some repetition (also the static analyzer is complaining), maybe it would be good to extract the part between here and the Copy to a separate function?


<!-- Sent from Reviewable.io -->

2021-09-01 15:22 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2460)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @acud)

___
*[pkg/api/pss.go, line 75 at r3](https://reviewable.io/reviews/ethersphere/bee/2460#-MiWvVqYBGXIJAzStSUm:-MiWwmoy6Sy5XJozyjk4:b-soz29b) ([raw file](https://github.com/ethersphere/bee/blob/c2a7a6bd759671652a7cb30773a6530e80fc5a17/pkg/api/pss.go#L75)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

since there's some repetition (also the static analyzer is complaining), maybe it would be good to extract the part between here and the Copy to a separate function?
</blockquote></details>

I need to confirm it first but it seems that we have a router middleware that already takes care of this (ReadMaxBytes).
If this is the case I will close this PR altogether...


<!-- Sent from Reviewable.io -->

2021-09-02 09:29 UTC, notanatol commented
All the http routes that receive content are wrapped in a `NewMaxBodyBytesHandler` that makes sure that the content size is limited.

2021-09-02 09:29 UTC, closed without merging