fix: avoid advertising priavte peers to the public network
ethersphere/bee pull request #2538
Opened 2021-09-23 11:01 UTC by mrekucci

2021-09-23 11:36 UTC, janos approved these changes
Nice. It would be good to have a test to ensure that the feature is not broken in the future by accident.

2021-09-23 11:52 UTC, aloknerurkar approved these changes

2021-09-23 12:46 UTC, istae commented on pkg/hive/hive.go
> +		if isPeerPublic && manet.IsPrivateAddr(addr.Underlay) {
maybe it's better to have this check under `BroadcastPeers` so that you can send full batches instead of skipping some here.

2021-09-23 12:46 UTC, istae commented on pkg/hive/hive.go
> +		if isPeerPublic && manet.IsPrivateAddr(addr.Underlay) {
can we also have this check before we attempt to ping the address under `checkAndAddPeers`

2021-09-23 17:16 UTC, acud requested changes
@mrekucci this might be a bit tricky... i'm not sure what's the cluster configuration in ci flow or in the large cluster tests. since private CIDRs may be used to advertise the nodes in these cases, the cluster might become completely defunct. we need to expose this via a CLI flag probably, in order to allow this to work in larger test networks. the reason that the beekeeper integration test is passing, is probably because all nodes explicitly dial to the bootnode on an internal network, and the cluster size is small, so full connectivity is preserved and no gossiping is needed

2021-09-27 12:41 UTC, mrekucci commented
> Nice. It would be good to have a test to ensure that the feature is not broken in the future by accident.

Done.

2021-09-27 12:41 UTC, mrekucci commented
> @mrekucci this might be a bit tricky... i'm not sure what's the cluster configuration in ci flow or in the large cluster tests. since private CIDRs may be used to advertise the nodes in these cases, the cluster might become completely defunct. we need to expose this via a CLI flag probably, in order to allow this to work in larger test networks. the reason that the beekeeper integration test is passing, is probably because all nodes explicitly dial to the bootnode on an internal network, and the cluster size is small, so full connectivity is preserved and no gossiping is needed

Done.

2021-09-27 16:21 UTC, janos approved these changes
Great!. LGTM.

2021-09-27 19:36 UTC, acud approved these changes
Nice! We need this flag to be added also to the helm chart and to beekeeper before this gets merged

2021-09-28 09:54 UTC, merged