feat: kademlia blocklists peer on ping timeout
ethersphere/bee pull request #2543
Opened 2021-09-27 13:02 UTC by istae

2021-09-27 13:07 UTC, istae commented on pkg/topology/kademlia/kademlia.go
> +			case <-time.After(5 * time.Second):
From metrics,

2021-09-27 14:15 UTC, mrekucci reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2543)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @acud, @mrekucci, and @notanatol)

___
*[pkg/blocker/blockler.go, line 17 at r2](https://reviewable.io/reviews/ethersphere/bee/2543#-MkbZJno0hvUvEwS4yuk:-MkbZJnt50Zrtgrw9xEj:b-92a525) ([raw file](https://github.com/ethersphere/bee/blob/aa248fedc36260c7ac277eefa06b7590f628564f/pkg/blocker/blockler.go#L17)):*
> ```Go
> 
> type peer struct {
> 	flagged    bool      // indicates whether the peer is actively flagged
> ```

You can get rid of the flagged field. Instead of this, you can use time zero value as a sentinel and as a result, the code will have more clarity.
___
*[pkg/blocker/blockler.go, line 65 at r2](https://reviewable.io/reviews/ethersphere/bee/2543#-Mkb_cF09SNaSZZOh9EQ:-Mkb_cF21l5m5SBfvILK:bo6qcyw) ([raw file](https://github.com/ethersphere/bee/blob/aa248fedc36260c7ac277eefa06b7590f628564f/pkg/blocker/blockler.go#L65)):*
As a first iteration this is good, just keep in mind that it can be quite memory intensive, see the documentation:

>  The underlying Timer is not recovered by the garbage collector
until the timer fires. If efficiency is a concern, use NewTimer
instead and call Timer.Stop if the timer is no longer needed.
___
*[pkg/p2p/p2p.go, line 38 at r2](https://reviewable.io/reviews/ethersphere/bee/2543#-MkbVtr_5ueM3UeyKcBC:-MkbVtrcBiMOvetaREcT:b-q6t1ge) ([raw file](https://github.com/ethersphere/bee/blob/aa248fedc36260c7ac277eefa06b7590f628564f/pkg/p2p/p2p.go#L38)):*
> ```Go
> 
> type Blocklister interface {
> 	// Blocklist will disconnect a peer and put it on a blocklist (blocking in & out connections) for provided duration
> ```

Missing period at the end of the sentence. The duration on the line below should be capitalized.


<!-- Sent from Reviewable.io -->

2021-09-27 15:09 UTC, notanatol approved these changes

2021-09-27 15:33 UTC, mrekucci approved these changes
> Reviewed 1 of 3 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)

___
*[pkg/blocker/blockler.go, line 22 at r5](https://reviewable.io/reviews/ethersphere/bee/2543#-MkbsV_H1Stun0PZ1sNi:-MkbsV_I1iOG2OQ1jMA5:b6i4liz) ([raw file](https://github.com/ethersphere/bee/blob/3aadd289c44096e18a9617e9d266fc11ceb703cc/pkg/blocker/blockler.go#L22)):*
> ```Go
> 
> var (
> 	wakeupTime time.Duration = time.Second * 10
> ```

This can be a constant.


<!-- Sent from Reviewable.io -->

2021-09-27 19:45 UTC, acud requested changes
> Reviewed 1 of 3 files at r3, 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2543)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @acud, @istae, and @mrekucci)

___
*[pkg/blocker/blockler.go, line 5 at r5](https://reviewable.io/reviews/ethersphere/bee/2543#-Mkckp7_5QsSObkxoKH6:-Mkckp7a9gv6CDHQ82Uc:b-ej6cyc) ([raw file](https://github.com/ethersphere/bee/blob/3aadd289c44096e18a9617e9d266fc11ceb703cc/pkg/blocker/blockler.go#L5)):*
> ```Go
> // license that can be found in the LICENSE file.
> 
> package blocker
> ```

file needs to be renamed
___
*[pkg/blocker/blockler.go, line 107 at r5](https://reviewable.io/reviews/ethersphere/bee/2543#-Mkclh0o0u7QdtjuMSWI:-Mkclh0o0u7QdtjuMSWJ:b-9ikvc1) ([raw file](https://github.com/ethersphere/bee/blob/3aadd289c44096e18a9617e9d266fc11ceb703cc/pkg/blocker/blockler.go#L107)):*
> ```Go
> // must be called only once.
> func (b *Blocker) Close() error {
> 	b.quit <- struct{}{}
> ```

it is better to close the channel since a naked write can block for a long time. also, since the worker goroutine might need to use the disconnecter interface even after the channel is closed, resulting in a panic (this is not the case right now, because the naked right makes sure that the synchronization happens in the correct way).


<!-- Sent from Reviewable.io -->

2021-09-28 07:54 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2543)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @acud, @istae, and @mrekucci)

___
*[pkg/blocker/blockler.go, line 22 at r5](https://reviewable.io/reviews/ethersphere/bee/2543#-MkbsV_H1Stun0PZ1sNi:-MkfNQNF4q4TW22_HGOK:bix74q6) ([raw file](https://github.com/ethersphere/bee/blob/3aadd289c44096e18a9617e9d266fc11ceb703cc/pkg/blocker/blockler.go#L22)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

This can be a constant.
</blockquote></details>

it's being overwritten in the `export_test.go` for the purpose of testing.


<!-- Sent from Reviewable.io -->

2021-09-29 08:35 UTC, acud approved these changes

2021-09-29 08:35 UTC, acud commented on pkg/blocker/blocker.go
> +			if err := b.disconnector.Blocklist(peer.addr, b.blockDuration, "blocker: flag timeout"); err != nil {
would be good to double check this doesn't panic on shutdown because of libp2p shutdown

2021-09-29 08:35 UTC, acud commented on pkg/blocker/blocker.go
> +		if !peer.blockAfter.IsZero() && time.Now().After(peer.blockAfter) {
adding an extra select here to check that the quit channel is closed would also speed up shutdown

2021-09-29 09:20 UTC, acud approved these changes

2021-09-29 09:36 UTC, merged