feat: Accounting info endpoint
ethersphere/bee pull request #2631
Opened 2021-10-29 14:50 UTC by metacertain

With growing payment thresholds, previous integration test checks have become partly obsolete, as the balances can no longer be verified against a global constant payment threshold used. 

In order to work around this, the /accounting endpoint displays beyond the balances the peer related other accounting variables, such as payment threshold given to and received from the peer.

A following up beekeeper [change](https://github.com/ethersphere/beekeeper/pull/205) adjusts the balance verification to happen against the variable payment thresholds displayed

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2631)

2021-11-09 08:20 UTC, mrekucci requested changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2631)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @metacertain and @mrekucci)

___
*[pkg/accounting/accounting.go, line 612 at r4](https://reviewable.io/reviews/ethersphere/bee/2631#-Mo2l9lz6nZ7jMUe20xm:-Mo2l9m4CoJSRe2PROrv:b51k34a) ([raw file](https://github.com/ethersphere/bee/blob/f1e107cdd535e1b4e254c42d589e877785a41fb8/pkg/accounting/accounting.go#L612)):*
> ```Go
> 
> 		balance, err := a.Balance(peerAddress)
> 		if err != nil {
> ```

Can be simplified as:
```golang
	if errors.Is(err, ErrPeerNoBalance) {
		balance = big.NewInt(0)
	} else if err != nil {
		return err, nil
	}
```
___
*[pkg/debugapi/router.go, line 245 at r4](https://reviewable.io/reviews/ethersphere/bee/2631#-Mo2lpsWCOq6st9kPwg9:-Mo2lpsXDthcPm0uNHeR:b-5slehl) ([raw file](https://github.com/ethersphere/bee/blob/f1e107cdd535e1b4e254c42d589e877785a41fb8/pkg/debugapi/router.go#L245)):*
> ```Go
> 	)
> 
> 	router.Handle("/accounting", jsonhttp.MethodHandler{
> ```

Missing Open API spec counterpart.


<!-- Sent from Reviewable.io -->

2021-12-03 09:31 UTC, acud requested changes

2021-12-03 09:31 UTC, acud commented on pkg/accounting/accounting.go
> +	Peer                  string
there's no need to represent the peer address twice. since the endpoint serializes a map with address as key, you're repeating the data here

2021-12-03 09:31 UTC, acud commented on pkg/accounting/accounting.go
> +func (a *Accounting) AccountingInfo() (map[string]PeerInfo, error) {
maybe `PeerAccounting`? info a bit general no?

2021-12-03 09:31 UTC, acud commented on pkg/debugapi/accounting_info.go
> +	InfoResponse []accountingInfoResponse `json:"infos"`
maybe we could find a better field name than `infos`?

2021-12-03 09:31 UTC, acud commented on pkg/debugapi/accounting_info.go
> +	Peer                  string         `json:"peer"`
since the map from the accounting package is already sorting entries by kv pairs (key is address, value is accounting data), you can omit this field

2021-12-03 09:31 UTC, acud commented on pkg/debugapi/accounting_info.go
> +	i := 0
i can be substituted by k, and `infoResponses` just a `map`

2021-12-14 01:49 UTC, acud commented
@metacertain are we still working on this?

2021-12-14 02:26 UTC, metacertain commented
> @metacertain are we still working on this?

yes

![image](https://user-images.githubusercontent.com/63165462/145921767-1261f5cb-247f-444f-b5c0-3549f404ef0d.png)

base PR needed unit tests first

2021-12-15 14:02 UTC, metacertain commented on pkg/debugapi/accounting_info.go
> +	errCantInfo = "Cannot get accounting infos"
No, this is not a go error, merely an HTTP error message

2021-12-15 15:23 UTC, mrekucci reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2631)* status: 1 of 11 files reviewed, 8 unresolved discussions (waiting on @acud, @metacertain, and @mrekucci)

___
*[openapi/SwarmDebug.yaml, line 44 at r14](https://reviewable.io/reviews/ethersphere/bee/2631#-MqycE8bEfi6i7NCN3JJ:-MqycE8bEfi6i7NCN3JK:b-of7whh) ([raw file](https://github.com/ethersphere/bee/blob/9069c0160dd50f9cd17bb0b640efeee45669b928/openapi/SwarmDebug.yaml#L44)):*
> ```YAML
>   "/accounting":
>     get:
>       summary: Get all accounting associated values with all known peers 
> ```

Unnecessary spaces at the end.
___
*[pkg/debugapi/accounting_info.go, line 15 at r6](https://reviewable.io/reviews/ethersphere/bee/2631#-MnBWuZBGHzJSXCR71Th-r6-15:-Mqyd1jc-RPJ3cM6Q1Pz:btovit) ([raw file](https://github.com/ethersphere/bee/blob/9ccac1044c463348148db2fe69c2459acacf36c5/pkg/debugapi/accounting_info.go#L15)):*
<details><summary><i>Previously, metacertain wrote…</i></summary><blockquote>

No, this is not a go error, merely an HTTP error message
</blockquote></details>

It should be a `const` and if it is an HTTP error message I suggest expressing this in the name, e.g.: `httpErrCantInfo`. Although I'd suggest using a more meaningful name, such as `httpErrGetAccountingInfo`.
Also, the abbreviation for information is info, not infos.


<!-- Sent from Reviewable.io -->

2021-12-15 16:36 UTC, metacertain commented
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2631)_ status: 1 of 11 files reviewed, 8 unresolved discussions (waiting on @acud, @metacertain, and @mrekucci)
> 
> _[openapi/SwarmDebug.yaml, line 44 at r14](https://reviewable.io/reviews/ethersphere/bee/2631#-MqycE8bEfi6i7NCN3JJ:-MqycE8bEfi6i7NCN3JK:b-of7whh) ([raw file](https://github.com/ethersphere/bee/blob/9069c0160dd50f9cd17bb0b640efeee45669b928/openapi/SwarmDebug.yaml#L44)):_
> 
> > ```yaml
> >   "/accounting":
> >     get:
> >       summary: Get all accounting associated values with all known peers 
> > ```
> 
> Unnecessary spaces at the end.
> 
> _[pkg/debugapi/accounting_info.go, line 15 at r6](https://reviewable.io/reviews/ethersphere/bee/2631#-MnBWuZBGHzJSXCR71Th-r6-15:-Mqyd1jc-RPJ3cM6Q1Pz:btovit) ([raw file](https://github.com/ethersphere/bee/blob/9ccac1044c463348148db2fe69c2459acacf36c5/pkg/debugapi/accounting_info.go#L15)):_
> 
> Previously, metacertain wrote…
> It should be a `const` and if it is an HTTP error message I suggest expressing this in the name, e.g.: `httpErrCantInfo`. Although I'd suggest using a more meaningful name, such as `httpErrGetAccountingInfo`. Also, the abbreviation for information is info, not infos.

applied

2021-12-16 15:39 UTC, acud approved these changes
nice

2021-12-16 15:39 UTC, acud commented on pkg/accounting/accounting.go
> +	// PeerAccountings returns the associated values for all known peers
PeerAccounting

2021-12-17 08:58 UTC, ralph-pichler commented on pkg/debugapi/export_test.go
> +	HttpErrGetAccountingInfo = httpErrGetAccountingInfo
why does this have a different naming convention than all the other errs?

2021-12-17 09:00 UTC, ralph-pichler approved these changes

2021-12-20 12:57 UTC, mrekucci approved these changes
> Reviewed 1 of 2 files at r7, 1 of 3 files at r9, 1 of 1 files at r17, 9 of 9 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2631)* status: all files reviewed, 10 unresolved discussions (waiting on @acud and @metacertain)



<!-- Sent from Reviewable.io -->

2021-12-20 19:52 UTC, acud approved these changes
LGTM minus Ralph's comment

2022-01-12 13:13 UTC, merged