test: add missing unit test for BeeNodeMode enum
ethersphere/bee pull request #2720
Opened 2021-12-07 11:46 UTC by nugaon

https://github.com/ethersphere/bee/pull/2649#discussion_r763010896

2021-12-07 11:54 UTC, acud requested changes

2021-12-07 11:54 UTC, acud commented on pkg/debugapi/node_test.go
> +package debugapi
this should be `debugapi_test`, the on line 12 `const nonExistingMode debugapi.BeeNodeMode`

2021-12-07 12:55 UTC, istae approved these changes

2021-12-07 15:35 UTC, aloknerurkar approved these changes

2021-12-07 20:49 UTC, acud approved these changes

2021-12-08 14:36 UTC, mrekucci commented on pkg/debugapi/node_test.go
> +			t.Fatalf("got unexpected bee node mode status string %q; wanted %q", have, want)
The error message is usually in the form of:  `"unexpected bee node mode: have %q; want %q"`.

2021-12-09 13:56 UTC, mrekucci commented
Nice, thanks!

2021-12-09 13:56 UTC, mrekucci approved these changes

2021-12-20 12:52 UTC, acud approved these changes

2021-12-20 12:53 UTC, merged