fix: unblocking write to channel in retrieval
ethersphere/bee pull request #2729
Opened 2021-12-09 16:28 UTC by metacertain

This change improves a rare edge case where the channel for results would be filled by asynchronous retrieves, removing the buffer for the channel

2021-12-09 18:12 UTC, acud requested changes
This also opens up another edge case, where because the polling goroutine is not yet listening to the response on the `select` on `L178`, the response is forever lost due to the `default` case being hit. I would advise against this

2021-12-09 19:00 UTC, metacertain commented
> This also opens up another edge case, where because the polling goroutine is not yet listening to the response on the `select` on `L178`, the response is forever lost due to the `default` case being hit. I would advise against this

When we receive a response, we always write that back in L161, and that happens in a goroutine, so blocking until the channel is free is not a problem there.

The empty result being wrote to the channel that gets a default case now only attempts to write to this channel to make sure the select in L178 doesn't block waiting as no new attempt was started in this iteration. 
If meanwhile there was a result wrote by one of the previous goroutines, this is not necessary, as the select will take that result immediately.

2021-12-10 18:33 UTC, acud approved these changes

2021-12-13 12:36 UTC, notanatol approved these changes

2021-12-13 12:58 UTC, mrekucci approved these changes

2021-12-13 15:20 UTC, merged