refactor: batchstore rewrite
ethersphere/bee pull request #2810
Opened 2022-02-10 14:38 UTC by istae

2022-02-17 16:56 UTC, mrekucci reviewed
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: all files reviewed, 1 unresolved discussion (waiting on @istae)

___
*[pkg/postage/batchstore/reserve.go, line 53 at r1](https://reviewable.io/reviews/ethersphere/bee/2810#-Mw7Tmkk9h01AnulicVo:-Mw7TmkoC0nmGvfy1oY0:b-qst7v5) ([raw file](https://github.com/ethersphere/bee/blob/ff624caf9837ffd01bc6514d8859c25146889348/pkg/postage/batchstore/reserve.go#L53)):*
> ```Go
> 	// Radius is the Radius of responsibility,
> 	// it defines the proximity order of chunks which we
> 	// would like to guarantee that all chunks are stored
> ```

Missin period at the end of the sentence.
___
*[pkg/postage/batchstore/reserve.go, line 346 at r1](https://reviewable.io/reviews/ethersphere/bee/2810#-Mw7WK5e-qigHl1WMjlV:-Mw7WK5e-qigHl1WMjlW:bay3usy) ([raw file](https://github.com/ethersphere/bee/blob/ff624caf9837ffd01bc6514d8859c25146889348/pkg/postage/batchstore/reserve.go#L346)):*
> ```Go
> 		err := s.evictFn(id)
> 		if err != nil {
> 			return err
> ```

Do we want to stop on the first error here, also below?
___
*[pkg/postage/batchstore/reserve_test.go, line 132 at r1](https://reviewable.io/reviews/ethersphere/bee/2810#-Mw7YmsWE7hCcADZctuc:-Mw7YmsWE7hCcADZctud:b-osadv8) ([raw file](https://github.com/ethersphere/bee/blob/ff624caf9837ffd01bc6514d8859c25146889348/pkg/postage/batchstore/reserve_test.go#L132)):*
> ```Go
> 
> 			for i, c := range tc.capacities[i] {
> 				cap := capacities[hex.EncodeToString((batches[i].ID))]
> ```

Redundant parentheses.


<!-- Sent from Reviewable.io -->

2022-02-22 21:06 UTC, acud requested changes
Amazing work @istae. I had a scan through this. Please note that there's a lot of comments about naming and term mixups, however they are not meant in any way to diminish the size of effort and achievement done here. Great stuff.
In general some recurring phenomena:
- the term capacity is often mixed up with the space that batches take up (not sure how to name it). `capacity != usage`. usage fills up capacity
- some indirection can be flattened with methods that are called from one place
- a few cases of defer statements that can be flattened to be executed after the code block they precede. this causes us to write non-linear code and it is not something that should go in a defer statement
- zero comments on tests :) we used to have a lot of comments on those tests. although their complexity has significantly improved, they are not trivial to read. It might useful to stress out the importance of this part of the codebase. It would be prudent to have as much possible documentation as we can here.
- it would also be good to know whether the beekeeper integration tests pass with minimal changes (I saw that some simple initial assertion is failing there). Since some of the code might need to change as a result. You can change the beekeeper branch with a workflow variable IIRC. Also, linking the beekeeper PR here for sake of clarity would be nice.

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810#-:-MwYC1s51VtPHJWUHFaR:b-g50477)* status: all files reviewed, 31 unresolved discussions (waiting on @istae)

___
*[pkg/postage/batchstore/reserve.go, line 46 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY--Bn3npWy4sEG_DQ:-MwY--Bn3npWy4sEG_DR:bismah4) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L46)):*
> ```Go
> var Capacity = exp2(22)
> 
> // fullEvictionRadius is a PO value used to fully dealloacte a batch.
> ```

"...when a batch expires"11
___
*[pkg/postage/batchstore/reserve.go, line 56 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-9Vv5k69APWiv_lK:-MwY-9Vv5k69APWiv_lL:bel9f2b) ([raw file](https://github.com/ethersphere/bee/blob/cc80f74c145b6e1c0e0e9e9be911892b4c83b6b9/pkg/postage/batchstore/reserve.go#L56)):*
> ```Go
> 	// it defines the proximity order of chunks which we
> 	// would like to guarantee that all chunks are stored
> 	Radius uint8 `json:"radius"`
> ```

I think that JSON annotations were used since we were persisting this. Is it no longer the case?
___
*[pkg/postage/batchstore/reserve.go, line 63 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-J8G7KnBdMtoCJQL:-MwY-J8G7KnBdMtoCJQM:bk0ql08) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L63)):*
> ```Go
> }
> 
> // allocateBatch is the main point of entry for a new batch.
> ```

`allocateBatch allocates a newly created batch`....
___
*[pkg/postage/batchstore/reserve.go, line 66 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-XS25L3qLsPcgWrY:-MwY-XS25L3qLsPcgWrZ:b-hm9e61) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L66)):*
> ```Go
> // After computing a new radius, the available capacity of the node is deducted
> // using the new batch's depth.
> // Must be called under the mutex lock.
> ```

`Must be called under lock.`
___
*[pkg/postage/batchstore/reserve.go, line 84 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY11dj-ObDFTErRPku:-MwY11dj-ObDFTErRPkv:budnr49) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L84)):*
> ```Go
> 
> 	var capacity int64
> 	if b.Depth > s.rs.Radius {
> ```

this is a bit of a quirk that I'm not sure how it will unfold (there's also no comment on this edge case), but what happens if indeed the batch depth is smaller than the radius? the batch is then unaccounted for and can still take up space in the reserve (btw the situation is possible if you execute the transaction directly with the contract)
___
*[pkg/postage/batchstore/reserve.go, line 85 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY0i6778pSkaj0DKre:-MwY0i6778pSkaj0DKrf:b5o1604) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L85)):*
> ```Go
> 	var capacity int64
> 	if b.Depth > s.rs.Radius {
> 		capacity = exp2(uint(b.Depth) - uint(s.rs.Radius))
> ```

some terms conflated here... capacity would make you think about the node's storage capacity. also, the batch doesn't have `capacity` but rather _usage_ ?
___
*[pkg/postage/batchstore/reserve.go, line 94 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY4LkWAQy2fse3EnVm:-MwY4LkWAQy2fse3EnVn:b-jmdl69) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L94)):*
> ```Go
> 	err = s.gainCapacity(b.Value)
> 	if err != nil {
> 		return fmt.Errorf("batchstore: allocate batch gain capacity %x %w", b.ID, err)
> ```

usually when wrapping we use `... : %w` (missing semicolon before the `%w` verb, would be good to scan through the PR to see this isn't recurring elsewhere)
___
*[pkg/postage/batchstore/reserve.go, line 117 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-xHs4DmCiDZMFX4O:-MwY-xHs4DmCiDZMFX4P:b-7dwrs7) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L117)):*
> ```Go
> }
> 
> // cleanup evicts and removes negative value batches.
> ```

`cleanup evicts and removes expired batch` there exists no concept as `negative value batch`
___
*[pkg/postage/batchstore/reserve.go, line 151 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2n_68tPsC5TRba-E:-MwY2n_68tPsC5TRba-F:b-wfla3j) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L151)):*
> ```Go
> 	})
> 	if err != nil {
> 		return err
> ```

kinda sucks but if the operation failed in the middle you're basically in an inconsistent state since you've already done capacity adjustments. it would be good to have atomic operations whenever possible, if it all.
___
*[pkg/postage/batchstore/reserve.go, line 154 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2YXc17MNh-DyncDg:-MwY2YXc17MNh-DyncDh:b6d2j2h) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L154)):*
> ```Go
> 	}
> 
> 	return s.evict(tofullyEvict)
> ```

if `evict` is used only here, why not inline the code here?
___
*[pkg/postage/batchstore/reserve.go, line 187 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2BLy5fJPJqtgRpsW:-MwY2BLy5fJPJqtgRpsX:b-avujv5) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L187)):*
> ```Go
> }
> 
> // gainCapacity iterates on the list of batches in ascending order of value and unreserves batches with the new radius
> ```

comment is incomprehensible :) which new radius? it is not provided. what if the radius didn't change? should we still call this method?
___
*[pkg/postage/batchstore/reserve.go, line 190 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY4baBE__I55dr4pO1:-MwY4baBE__I55dr4pO2:b-l9vjd) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L190)):*
> ```Go
> // until a positive node capacity is reached.
> // Must be called under the mutex lock.
> func (s *store) gainCapacity(upto *big.Int) error {
> ```

Not sure why exactly it is called _gain_ capacity; capacity is adjusted here, it can decrease (since there are more ba [...]

2022-02-23 22:56 UTC, istae reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: 6 of 10 files reviewed, 31 unresolved discussions (waiting on @acud, @istae, and @mrekucci)

___
*[pkg/postage/batchstore/reserve.go, line 46 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY--Bn3npWy4sEG_DQ:-MwcfSq-9tyeYGtxs9Ym:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L46)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

"...when a batch expires"11
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 56 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-9Vv5k69APWiv_lK:-MwcfcyD7e-0FDxLb1F0:b5oy9gl) ([raw file](https://github.com/ethersphere/bee/blob/cc80f74c145b6e1c0e0e9e9be911892b4c83b6b9/pkg/postage/batchstore/reserve.go#L56)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I think that JSON annotations were used since we were persisting this. Is it no longer the case?
</blockquote></details>

We are still persisting this struct but the annotations are not needed as all of the fields are public. 
___
*[pkg/postage/batchstore/reserve.go, line 63 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-J8G7KnBdMtoCJQL:-Mwcg6Aj8kpHEl2uI3kq:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L63)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`allocateBatch allocates a newly created batch`....
</blockquote></details>

Done.



_Code quote:_
```Go
allocateBatch is the main point of entry for a new batch
```
___
*[pkg/postage/batchstore/reserve.go, line 66 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-XS25L3qLsPcgWrY:-MwcgDNE8P61oK1Iq2LT:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L66)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`Must be called under lock.`
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 84 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY11dj-ObDFTErRPku:-MwcgEgX6yvAUMhWfzvl:bgbvtr1) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L84)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this is a bit of a quirk that I'm not sure how it will unfold (there's also no comment on this edge case), but what happens if indeed the batch depth is smaller than the radius? the batch is then unaccounted for and can still take up space in the reserve (btw the situation is possible if you execute the transaction directly with the contract)
</blockquote></details>

So batches whose depth is lower than the reserve state radius as a result of uniform distribution of chunk hashes are unlikely to contain chunks with POs greater than or equal to the node's current reserve state radius. As such, the node allocates zero capacity for the batch. But, we must still take the batch into account when calculating radius.
___
*[pkg/postage/batchstore/reserve.go, line 85 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY0i6778pSkaj0DKre:-MwchOR-7chkt1vqOi42:b-p4837j) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L85)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

some terms conflated here... capacity would make you think about the node's storage capacity. also, the batch doesn't have `capacity` but rather _usage_ ?
</blockquote></details>

variable removed
___
*[pkg/postage/batchstore/reserve.go, line 94 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY4LkWAQy2fse3EnVm:-MwchgXcCbx7hR59-ZO4:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L94)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

usually when wrapping we use `... : %w` (missing semicolon before the `%w` verb, would be good to scan through the PR to see this isn't recurring elsewhere)
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 117 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY-xHs4DmCiDZMFX4O:-Mwchm-a95j7_28sccnS:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L117)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`cleanup evicts and removes expired batch` there exists no concept as `negative value batch`
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 154 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2YXc17MNh-DyncDg:-MwciopH-E74JEkkj5G6:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L154)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

if `evict` is used only here, why not inline the code here?
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 187 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2BLy5fJPJqtgRpsW:-MwcjANPDlOO-k5tAAbI:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L187)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

comment is incomprehensible :) which new radius? it is not provided. what if the radius didn't change? should we still call this method?
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 233 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY7czI5MyVZTPUiJOo:-MwckYTR5v_suB2ilPfX:b-3fahr9) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L233)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

the first return value of `capacity` is always ignored, why return it?
</blockquote></details>

the unit tests needed them, but I found a new solution now, thanks.
___
*[pkg/postage/batchstore/reserve.go, line 250 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY76N69-QD5XZPd-yb:-Mwcm89217uxfuL2ZWIe:buy864g) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L250)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

again capacity is a misleading term. it means the capacity to store things, not how much space things take up
</blockquote></details>

So I went with the term "commitment" everywhere
___
*[pkg/postage/batchstore/reserve.go, line 258 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY6tYYBqXQrBOFIQxL:-Mwcn32D6UQKqk60QPyz:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L258)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

not sure where "eviction radius" came from... there's no notion of eviction radius here no?
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 279 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY6IPZ0rw08SjLikz_:-MwcmTy06OYb4KmHPf8v:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L279)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

..not sure why this is in a defer statement... can't we have sequential procedural code? 
</blockquote></details>

Done.



_Co [...]

2022-02-24 14:34 UTC, istae reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: 6 of 10 files reviewed, 31 unresolved discussions (waiting on @acud, @istae, and @mrekucci)

___
*[pkg/postage/batchstore/reserve.go, line 384 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY7yBH1tPquFHo61j0:-Mwg61qwA-t4670JjLJs:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L384)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this should be structured after the `Iterate` call
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve_test.go, line 391 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYBOJq-akpuQiB0pfV:-Mwg7DJYD3xi2uVwzxJk:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve_test.go#L391)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

directly use `t.TempDir()`
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve_test.go, line 395 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYBSrL-IXHlOeGV3kR:-Mwg7D3j6GLVix0X3Qie:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve_test.go#L395)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

not needed when using `t.TempDir()`
</blockquote></details>

Done.



_Code quote:_
```Go
dir, err := os.MkdirTemp("", "batchstore_test")
```
___
*[pkg/postage/batchstore/reserve_test.go, line 439 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYBZAgBqvQITtzsSMh:-Mwg7c9Y43Bh9gUNWgEm:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve_test.go#L439)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

term mixup
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/store.go, line 292 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYBpno0bH3lzQnKn73:-Mwg7f8v3_Ob8PBrSKp6:bbdcxe) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/store.go#L292)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

Do we actually still need to track the individual batch radius? afaik this was never used and I'm not sure if it is still needed. I remember we just need to track the storage radius, as the upper bound radius is global, no?
</blockquote></details>

When a new batch is created, the radius may increase, so we need to increase the radius of enough batches until we have positive reserve state available.
To compute the change of commitment as a result of changing the radius, we need the old radius.


<!-- Sent from Reviewable.io -->

2022-02-28 18:01 UTC, mrekucci approved these changes
> Reviewed 2 of 4 files at r3, 4 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: 8 of 11 files reviewed, 31 unresolved discussions (waiting on @acud, @istae, and @mrekucci)



<!-- Sent from Reviewable.io -->

2022-03-01 15:12 UTC, acud requested changes
> Reviewed 1 of 4 files at r3, 1 of 4 files at r4, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: 10 of 11 files reviewed, 18 unresolved discussions (waiting on @istae and @mrekucci)

___
*[pkg/postage/batchstore/export_test.go, line 13 at r3](https://reviewable.io/reviews/ethersphere/bee/2810#-MwgXv4GDi_FeWqV8fkM:-MwgXv4GDi_FeWqV8fkN:borhpqk) ([raw file](https://github.com/ethersphere/bee/blob/d3b137e8bce1f4bb3dc4e467a2892b1a870c4033/pkg/postage/batchstore/export_test.go#L13)):*
> ```Go
> // ChainStateKey is the statestore key for the chain state.
> const StateKey = chainStateKey
> const BatchstoreVersion = batchstoreVersion
> ```

leftovers?
___
*[pkg/postage/batchstore/reserve.go, line 84 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY11dj-ObDFTErRPku:-Mwga45A1FQ9bzUQ9tPp:bwrtht9) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L84)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

So batches whose depth is lower than the reserve state radius as a result of uniform distribution of chunk hashes are unlikely to contain chunks with POs greater than or equal to the node's current reserve state radius. As such, the node allocates zero capacity for the batch. But, we must still take the batch into account when calculating radius.
</blockquote></details>

cool, can we have a comment about this in the code then? :)
___
*[pkg/postage/batchstore/reserve.go, line 190 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY4baBE__I55dr4pO1:-Mx4xy6d-9q2lC0RC58d:b-wxqufr) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L190)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

Not sure why exactly it is called _gain_ capacity; capacity is adjusted here, it can decrease (since there are more batches) or decrease (since a batch expired).

A note about `upto` - this is an interval and it is usual to define whether the interval is closed or open
</blockquote></details>

can we improve on this somehow?
___
*[pkg/postage/batchstore/reserve.go, line 250 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY76N69-QD5XZPd-yb:-MwgatVm6D4YK7KwqwdJ:b-qz7cg) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L250)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

So I went with the term "commitment" everywhere
</blockquote></details>

amazing thanks!
___
*[pkg/postage/batchstore/reserve.go, line 368 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4y6af-ybX_gRNOnce:-Mx4y6af-ybX_gRNOncf:b48zqtg) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve.go#L368)):*
> ```Go
> func (s *store) Unreserve(cb postage.UnreserveIteratorFn) error {
> 
> 	now := time.Now()
> ```

you're measuring how long it takes to acquire the lock too here. it would be good to have separate metrics for how long it takes with and without acquiring the lock, similarly to how we do this in the localstore
___
*[pkg/postage/batchstore/reserve_test.go, line 53 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4yX4B3-Doyx4AdbIr:-Mx4yX4B3-Doyx4AdbIs:b-x5tn3) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L53)):*
> ```Go
> 	// 1)	the commitment values inside the commitment slice
> 	// 		is checked against the commitment allocated in the batchstore,
> 	// 2) 	the the sum of reservate state available and commitments should never exceed 32 chunks.
> ```

the the...
___
*[pkg/postage/batchstore/reserve_test.go, line 54 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4ycVK3sKc_Oex5RPR:-Mx4ycVK3sKc_Oex5RPS:b2nh7vw) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L54)):*
>=0
___
*[pkg/postage/batchstore/reserve_test.go, line 93 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4yz6_-ML0ISLYZlNg:-Mx4yz6_-ML0ISLYZlNh:b-kvqf43) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L93)):*
> ```Go
> 				{depth: initDepth, value: 2},
> 			},
> 			commitment: [][]int64{{32}, {16, 16}, {8, 16, 8}},
> ```

since they are all the same depth, how is it that when all three are added that you expect 8,16,8? the first test case is very similar and shows 8,8,8 which is what i would expect here no?
___
*[pkg/postage/batchstore/reserve_test.go, line 109 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4zFsl0Jrcbpa9XdVw:-Mx4zFsl0Jrcbpa9XdVx:bps1s89) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L109)):*
> ```Go
> 				{depth: initDepth, value: 3},
> 			},
> 			commitment: [][]int64{{32}, {16, 16}, {16, 8, 8}},
> ```

here too
___
*[pkg/postage/batchstore/reserve_test.go, line 117 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx5-z5i9gsMQmK5yn5H:-Mx5-z5i9gsMQmK5yn5I:by2h1ho) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L117)):*
> ```Go
> 				{depth: initDepth + 5, value: 5},
> 			},
> 			commitment: [][]int64{{32}, {16, 16}, {0, 0, 16}},
> ```

so from the first two batches you don't account anything? also, it would be good to have comments for each test case why the results are the way they are....
___
*[pkg/postage/batchstore/store.go, line 292 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYBpno0bH3lzQnKn73:-Mx51Iem4JkIPAOwxMnN:blfhobn) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/store.go#L292)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

When a new batch is created, the radius may increase, so we need to increase the radius of enough batches until we have positive reserve state available.
To compute the change of commitment as a result of changing the radius, we need the old radius.
</blockquote></details>

but can't you just use the reserve radius directly from the reserve state?
___
*[pkg/postage/batchstore/store.go, line 88 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx50so_BVHLeaTsuKpY:-Mx50so_BVHLeaTsuKpZ:bqzn0wo) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/store.go#L88)):*
> ```Go
> 	// check batchstore version
> 	var migrated bool
> 	err = st.Get(batchstoreVersion, &migrated)
> ```

did we end up having a migration finally?  i thought you're going to do this directly from the statestore migration, no need to introduce another layer of migrations inside the components...
___
*[pkg/postage/batchstore/store_test.go, line 226 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx51SUoAYd1JFeuvnL7:-Mx51SUoAYd1JFeuvnL8:b-b2sjqd) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/store_test.go#L226)):*
> ```Go
> }
> 
> func TestBatchStore_Migrate(t *testing.T) {
> ```

can be avoided when using the statestore migration


<!-- Sent from Reviewable.io -->

2022-03-08 03:34 UTC, acud requested changes
Looks great.
Few comments
- it would be good to mark addressed comments as resolved
- table driven tests could be structured a tiny bit better

> Reviewed 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810#-:-Mxb_FzJ6QohlZvdDR29:be6khw5)* status: all files reviewed, 8 unresolved discussions (waiting on @istae and @zelig)

___
*[pkg/postage/batch.go, line 21 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-Mxb_Xdw71hKLj6Q9kvl:-Mxb_Xdx5ygxfQVR0J4c:b-11vj1m) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batch.go#L21)):*
> ```Go
> 	BucketDepth uint8    // the depth of neighbourhoods t
> 	Immutable   bool     // if the batch allows adding new capacity (dilution)
> 	Radius      uint8    // reserve radius
> ```

So this field was not just never serialized but also never used. Now we've repurposed it to be the _storage_ radius, but the remark still says reserve radius (??) which is pretty much irrelevant at this stage. It would also do grace to name the field in a way which is reflective of its purpose, hence `StorageRadius` might be more appropriate here maybe?
___
*[pkg/postage/batchstore/reserve_test.go, line 303 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYAPOq8v8bX_rkBhG4:-MxbZBVCC7RMEpgkX7la:b-pvbpn3) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve_test.go#L303)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this block is copy pasted everywhere and can be pulled out into a test helper that would do exactly this. also, it would be nice to reduce the boilerplate overhead when writing table-driven tests like:
```go
for _,tc := range []struct {
  name string 
  add ....
  ....
} { 
 {
   name: "...",
   add: ....
}, {
 ....
},
} {
 <execute test code here>
}
```
</blockquote></details>

not addressed (not here neither in other places). nitpick but still easier to read table driven tests this way. won't block tho if you insist of having it this way....
___
*[pkg/postage/batchstore/reserve_test.go, line 22 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-MxbYTxMDxPK5BAozZIZ:-MxbYTxNDbac0ti6JWux:b9xqhyr) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/reserve_test.go#L22)):*
> ```Go
> 	depth  uint8
> 	value  int
> 	radius uint8
> ```

it would be good to comment what this means... i realized only too late that this is the assertion for the reserve radius, not batch radius. at first glance this seems related to the batch itself, but it relates to the whole reserve. personally i would find it more readable that the expectations are done after all batches are added in a certain case. so the case would have an `add` field and also an `expect` field that would in turn have `radius`, and other fields as needed (maybe also total commitment?)
___
*[pkg/postage/batchstore/store.go, line 232 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-Mxb_2Ou6iMlX-Jhk9Vj:-Mxb_2Ou6iMlX-Jhk9Vk:bfj4dwc) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/store.go#L232)):*
> ```Go
> // ones before it stores the chain state in the store.
> func (s *store) PutChainState(cs *postage.ChainState) error {
> 	s.cs = cs
> ```

this should be _after_ acquiring the mutex... why did it move?


<!-- Sent from Reviewable.io -->

2022-03-08 06:09 UTC, zelig approved these changes
> Reviewed 1 of 10 files at r1, 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: all files reviewed, 8 unresolved discussions (waiting on @istae)



<!-- Sent from Reviewable.io -->

2022-03-08 12:18 UTC, istae reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: all files reviewed, 9 unresolved discussions (waiting on @acud, @istae, and @mrekucci)

___
*[pkg/debugapi/postage.go, line 320 at r1](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx_W-fv-Vqdr4eizzvm:-MxdLASc36hlI55G01nx:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/ff624caf9837ffd01bc6514d8859c25146889348/pkg/debugapi/postage.go#L320)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

This should be removed from the OpenAPI `SwarmCommon.yaml` `ReserveState` declaration and the whole `ReserveState` should be updated since it doesn't match the response anymore.
</blockquote></details>

Done.
___
*[pkg/postage/batch.go, line 21 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-Mxb_Xdw71hKLj6Q9kvl:-MxdLWRY0Mz07fuEgQFK:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batch.go#L21)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

So this field was not just never serialized but also never used. Now we've repurposed it to be the _storage_ radius, but the remark still says reserve radius (??) which is pretty much irrelevant at this stage. It would also do grace to name the field in a way which is reflective of its purpose, hence `StorageRadius` might be more appropriate here maybe?
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/export_test.go, line 13 at r3](https://reviewable.io/reviews/ethersphere/bee/2810#-MwgXv4GDi_FeWqV8fkM:-MxYiRqd1Rq5iN4dK9v6:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d3b137e8bce1f4bb3dc4e467a2892b1a870c4033/pkg/postage/batchstore/export_test.go#L13)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

leftovers?
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 84 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY11dj-ObDFTErRPku:-MxdLXXnE_P2HFQaBPx1:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L84)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

cool, can we have a comment about this in the code then? :)
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 151 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwY2n_68tPsC5TRba-E:-MxdLjcxEmERMyxS_X-N:b-g243zw) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve.go#L151)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

kinda sucks but if the operation failed in the middle you're basically in an inconsistent state since you've already done capacity adjustments. it would be good to have atomic operations whenever possible, if it all.
</blockquote></details>

not sure how to improve the situation than what is it now, I am open to suggestions however.
___
*[pkg/postage/batchstore/reserve_test.go, line 303 at r2](https://reviewable.io/reviews/ethersphere/bee/2810#-MwYAPOq8v8bX_rkBhG4:-MxdP2_cDSbSSJctOPyK:b-na9tww) ([raw file](https://github.com/ethersphere/bee/blob/9309f534868a24720e457b3765e128cfd6cc80f0/pkg/postage/batchstore/reserve_test.go#L303)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

not addressed (not here neither in other places). nitpick but still easier to read table driven tests this way. won't block tho if you insist of having it this way....
</blockquote></details>

I'd rather keep the way it is at the moment. If other team members insist on this topic, I don't mind changing the style. 
___
*[pkg/postage/batchstore/reserve_test.go, line 109 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx4zFsl0Jrcbpa9XdVw:-MxdNBQkBRrNCggNhUaV:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L109)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve_test.go, line 117 at r8](https://reviewable.io/reviews/ethersphere/bee/2810#-Mx5-z5i9gsMQmK5yn5H:-MxdNCTQ5vsu3b76nYnm:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/f255d047f05aba3463b867a9b1f021013039f58f/pkg/postage/batchstore/reserve_test.go#L117)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

so from the first two batches you don't account anything? also, it would be good to have comments for each test case why the results are the way they are....
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve_test.go, line 22 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-MxbYTxMDxPK5BAozZIZ:-MxdMX_SCWuZ5B30OcGP:bxue15t) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/reserve_test.go#L22)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

it would be good to comment what this means... i realized only too late that this is the assertion for the reserve radius, not batch radius. at first glance this seems related to the batch itself, but it relates to the whole reserve. personally i would find it more readable that the expectations are done after all batches are added in a certain case. so the case would have an `add` field and also an `expect` field that would in turn have `radius`, and other fields as needed (maybe also total commitment?)
</blockquote></details>

I prefer the current way of checking the reserve radius at every step. I've renamed the field to be `reserveRadius` and added new comments.
The explicit radius testing also tests total commitment implicitly, plus we no longer have  have an available field, so not sure what to tests against exactly.
___
*[pkg/postage/batchstore/store.go, line 232 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-Mxb_2Ou6iMlX-Jhk9Vj:-MxdSwZn2pmlf4UUOTYw:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/store.go#L232)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this should be _after_ acquiring the mutex... why did it move?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-08 15:03 UTC, acud approved these changes
> Reviewed 17 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: all files reviewed, 3 unresolved discussions (waiting on @aloknerurkar, @istae, and @mrekucci)

___
*[pkg/postage/batchstore/reserve.go, line 206 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-MvZ3YVXCB3SLhcLvvaw-r9-206:-Mxe1k4x1s5algjvzmn4:b-7hbprb) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/reserve.go#L206)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

Value of the top-level `stopped` is masked here.
</blockquote></details>

wdym?
___
*[pkg/postage/batchstore/reserve_test.go, line 22 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-MxbYTxMDxPK5BAozZIZ:-Mxe20F90HPV7AFYnkHo:b7f699g) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/reserve_test.go#L22)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

I prefer the current way of checking the reserve radius at every step. I've renamed the field to be `reserveRadius` and added new comments.
The explicit radius testing also tests total commitment implicitly, plus we no longer have  have an available field, so not sure what to tests against exactly.
</blockquote></details>

it tests commitment implicitly in the cases where the radius has indeed changed. it would be nice to delineate exactly in which points the radius changes against the commitment. it would make the test more readable and the underlying logic more legible. the point of these unit tests are not just to test the code, but also teach others and allow for onboarding. please bear that in mind.


<!-- Sent from Reviewable.io -->

2022-03-08 15:09 UTC, mrekucci approved these changes
> Reviewed 17 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2810)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar and @istae)



<!-- Sent from Reviewable.io -->

2022-03-09 07:31 UTC, aloknerurkar commented
___
*[pkg/postage/batchstore/reserve.go, line 206 at r9](https://reviewable.io/reviews/ethersphere/bee/2810#-MvZ3YVXCB3SLhcLvvaw-r9-206:-MxhZqsf6Cpm-tef5U0m:b-ld2p4z) ([raw file](https://github.com/ethersphere/bee/blob/8ed4c4bb0dde43072994d9abc0fdd595fe0e6780/pkg/postage/batchstore/reserve.go#L206)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

wdym?
</blockquote></details>

So `stopped` is defined before the iterate call. It is being checked below after the Iterate call returns to see if full iteration happened. If I am not mistaken, the code expects the value of stopped to be filled here? But this is creating a new variable due to the `:=`

Right now, the value of stopped is not changed anywhere. So the `if !stopped` below is always true.


<!-- Sent from Reviewable.io -->

2022-03-09 13:08 UTC, istae commented on pkg/postage/batchstore/reserve.go
> +		stopped, err := cb(id, b.Radius)
Good catch, thanks @aloknerurkar 🙏

2022-03-22 11:11 UTC, aloknerurkar commented on pkg/postage/batchstore/reserve.go
> +		b.StorageRadius++
Can we add some comment here to say why this is being increased?

2022-03-22 12:40 UTC, istae commented on .github/patches/postagereserve.patch
> -> var DefaultDepth = uint8(2) // 12 is the testnet depth at the time of merging to master
file is completely deleted.

2022-03-23 07:16 UTC, aloknerurkar approved these changes

2022-04-11 23:02 UTC, merged