fix: reset stream on addcontextheader fail
ethersphere/bee pull request #2885
Opened 2022-04-13 12:20 UTC by metacertain

2022-04-13 12:47 UTC, mrekucci requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2885)* status: all files reviewed, 1 unresolved discussion (waiting on @metacertain)

___
*[pkg/p2p/libp2p/libp2p.go, line 843 at r1](https://reviewable.io/reviews/ethersphere/bee/2885#-N-XxVsTEi6cwTAzTD9H:-N-XxVsTEi6cwTAzTD9I:bp75e8q) ([raw file](https://github.com/ethersphere/bee/blob/e2b87ee90d100c3623e5d93559676181ec4cb116/pkg/p2p/libp2p/libp2p.go#L843)):*
> ```Go
> 	}
> 	if err := s.tracer.AddContextHeader(ctx, headers); err != nil && !errors.Is(err, tracing.ErrContextNotFound) {
> 		s.logger.Errorf("new stream add context header: %w", err)
> ```

The `%w` verb is not supported by the logger, use `%v` instead.


<!-- Sent from Reviewable.io -->

2022-04-13 13:30 UTC, acud requested changes

2022-04-14 12:30 UTC, acud approved these changes
Thanks!

2022-04-14 14:36 UTC, mrekucci reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2885)* status: all files reviewed, 2 unresolved discussions (waiting on @metacertain)



<!-- Sent from Reviewable.io -->

2022-04-15 08:09 UTC, merged