feat: improve resilience on hibernation and network failure
ethersphere/bee pull request #2887
Opened 2022-04-13 19:09 UTC by mrekucci

- don't blocklist peers after waking up from hibernation
- don't blocklist peers as a consequence of a network outage
- keep the known peers list stable during the network outage
- expose network status indicator on the kademlia topology endpoint

2022-04-13 20:06 UTC, notanatol approved these changes

2022-04-14 16:18 UTC, janos approved these changes

2022-04-14 20:38 UTC, acud requested changes
Nice and thorough! I have a small nitpick and another concern about online-ness assumptions.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2887#-:-N-dmsTyE6WPTqZkxVTG:b-64bid3)* status: all files reviewed, 2 unresolved discussions (waiting on @mrekucci and @ralph-pichler)

___
*[pkg/p2p/libp2p/libp2p.go, line 604 at r1](https://reviewable.io/reviews/ethersphere/bee/2887#-N-dlUsc4nkV4wCyk3Q4:-N-dlUsc4nkV4wCyk3Q5:b-7h3xko) ([raw file](https://github.com/ethersphere/bee/blob/b1e4d03206469342a98148c1910d9b89b9b3f541/pkg/p2p/libp2p/libp2p.go#L604)):*
> ```Go
> func (s *Service) Blocklist(overlay swarm.Address, duration time.Duration, reason string) error {
> 	if s.NetworkStatus() != p2p.NetworkStatusAvailable {
> 		return nil
> ```

nit, but I'm not sure that silencing the error here is the preferred way to go. Perhaps returning an explicit error that an attempt to blocklist has been made while offline and allowing it to bubble and logging wherever necessary could be preferable, even if for the sake of debugging corner cases. Up to you...
___
*[pkg/p2p/libp2p/libp2p.go, line 1004 at r1](https://reviewable.io/reviews/ethersphere/bee/2887#-N-dmDiN0cTe-NLxnUfu:-N-dmDiN0cTe-NLxnUfv:b-dwrss5) ([raw file](https://github.com/ethersphere/bee/blob/b1e4d03206469342a98148c1910d9b89b9b3f541/pkg/p2p/libp2p/libp2p.go#L1004)):*
> ```Go
> 			err = p2p.ErrNetworkUnavailable
> 		}
> 	case isNetworkOrHostUnreachableError(err):
> ```

careful... will this be also triggered if we are online and the target peer is offline? a boolean might not shine here very well... that's why libp2p's autonat uses a scoring system that adds and subtracts points from a counter in order to achieve more certainty about a node's reachability status


<!-- Sent from Reviewable.io -->

2022-04-19 14:50 UTC, mrekucci reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2887)* status: all files reviewed, 1 unresolved discussion (waiting on @acud and @ralph-pichler)

___
*[pkg/p2p/libp2p/libp2p.go, line 604 at r1](https://reviewable.io/reviews/ethersphere/bee/2887#-N-dlUsc4nkV4wCyk3Q4:-N01E7erEUdwYG_GI98M:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/b1e4d03206469342a98148c1910d9b89b9b3f541/pkg/p2p/libp2p/libp2p.go#L604)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

nit, but I'm not sure that silencing the error here is the preferred way to go. Perhaps returning an explicit error that an attempt to blocklist has been made while offline and allowing it to bubble and logging wherever necessary could be preferable, even if for the sake of debugging corner cases. Up to you...
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 1004 at r1](https://reviewable.io/reviews/ethersphere/bee/2887#-N-dmDiN0cTe-NLxnUfu:-N01ELpsBSw3z2Qh2zSB:b-j1b0vz) ([raw file](https://github.com/ethersphere/bee/blob/b1e4d03206469342a98148c1910d9b89b9b3f541/pkg/p2p/libp2p/libp2p.go#L1004)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

careful... will this be also triggered if we are online and the target peer is offline? a boolean might not shine here very well... that's why libp2p's autonat uses a scoring system that adds and subtracts points from a counter in order to achieve more certainty about a node's reachability status
</blockquote></details>

This function specifically checks for errors that are raised by the underlying operating system when a network failure occurs. There are two specific cases captured:
- when there is no network connection available on your local machine
- when your local network is not connected to the Internet

As for the scoring system, we already have something similar in the place, see `internal/breaker`. I originally started tuning this component, but it wasn't fast enough to reliably detect a network outage. I think as a first iteration this is good enough and we can iterate on it if new cases come up.


<!-- Sent from Reviewable.io -->

2022-04-19 18:49 UTC, acud approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)



<!-- Sent from Reviewable.io -->

2022-04-20 11:54 UTC, metacertain approved these changes

2022-04-20 12:02 UTC, merged