fix: wip
ethersphere/bee pull request #3052
Opened 2022-06-29 07:52 UTC by notanatol

### Checklist

- [X] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)

### Description
Sometimes we skip the closest peer because of overdraft. A potential solution would be to retry for peers in the skiplist that have been put there because overdraft reasons.

2022-06-29 17:03 UTC, istae approved these changes

2022-06-30 05:28 UTC, notanatol commented on pkg/pushsync/pushsync.go
> +				if skipPeers.OverdraftListEmpty() {
added

2022-06-30 07:21 UTC, aloknerurkar requested changes

2022-06-30 07:21 UTC, aloknerurkar commented on pkg/pushsync/pushsync.go
>  				continue
If we continue here after an errContinue, the select case would just hang. This assumes a push has been initiated and we wait for the resultChan to unblock us.

2022-06-30 11:53 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3052)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @acud, @aloknerurkar, @istae, @metacertain, @mrekucci, and @notanatol)

___
*[`pkg/skippeers/skip_peers.go` line 36 at r2](https://reviewable.io/reviews/ethersphere/bee/3052#-N5nuj_HA5yfwVDCswJh:-N5oRI2-5u61mpqQaQgz:b-d6t1pw) ([raw file](https://github.com/ethersphere/bee/blob/8634f24e2ac253f38dc2f3234c73f9427666de10/pkg/skippeers/skip_peers.go#L36)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

I'd suggest using `map` in order to avoid iterating the whole set before adding a new element.
</blockquote></details>

for small datasets a slice is cheaper than a map, if I'm not mistaken.


<!-- Sent from Reviewable.io -->

2022-06-30 13:31 UTC, mrekucci approved these changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3052)* status: all files reviewed, 3 unresolved discussions (waiting on @acud, @aloknerurkar, @istae, @metacertain, and @notanatol)

___
*[`pkg/skippeers/skip_peers.go` line 36 at r2](https://reviewable.io/reviews/ethersphere/bee/3052#-N5nuj_HA5yfwVDCswJh:-N5oncaW7SA_TUtf4XeK:b-lz8pvc) ([raw file](https://github.com/ethersphere/bee/blob/8634f24e2ac253f38dc2f3234c73f9427666de10/pkg/skippeers/skip_peers.go#L36)):*
<details><summary><i>Previously, notanatol (Anatol) wrote…</i></summary><blockquote>

for small datasets a slice is cheaper than a map, if I'm not mistaken.
</blockquote></details>

It's up to a ~100 entries.


<!-- Sent from Reviewable.io -->

2022-06-30 13:38 UTC, istae commented on pkg/pushsync/pushsync.go
> +var ErrNotAttempted = errors.New("peer not attempted")
no need to export, and can be moved to the top of the protocol

2022-06-30 13:38 UTC, istae commented on pkg/pushsync/pushsync.go
> +		errOverdraftNotEmpty = errors.New("continue")
replace with a better error message

2022-06-30 13:42 UTC, istae commented on pkg/pushsync/pushsync.go
> +			if retry {
much cleaner, thanks :)

2022-06-30 13:45 UTC, istae requested changes

2022-06-30 20:23 UTC, istae approved these changes

2022-07-01 13:15 UTC, aloknerurkar approved these changes

2022-07-04 05:30 UTC, metacertain approved these changes

2022-07-04 10:10 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3052)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @acud, @aloknerurkar, @istae, @metacertain, @mrekucci, and @notanatol)

___
*[`pkg/pushsync/pushsync.go` line 415 at r5](https://reviewable.io/reviews/ethersphere/bee/3052#-N5iR_rv5624rb4Qn9DZ-r5-415:-N67g98A8NFgXjN7oFek:bb7f2mf) ([raw file](https://github.com/ethersphere/bee/blob/b1358060cf362a93debdce19d209cd5cf672dd9c/pkg/pushsync/pushsync.go#L415)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

can be replaced with a variable, @metacertain is half a second sufficient?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-07-05 07:53 UTC, notanatol commented on pkg/skippeers/skip_peers.go
>  	return append(append(s.addresses[:0:0], s.addresses...), s.overdraftAddresses...)
fixed

2022-07-05 07:54 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3052)* status: 1 of 13 files reviewed, 8 unresolved discussions (waiting on @acud, @aloknerurkar, @istae, @metacertain, and @mrekucci)

___
*[`pkg/pushsync/pushsync.go` line 411 at r5](https://reviewable.io/reviews/ethersphere/bee/3052#-N5iR_rv5624rb4Qn9DZ-r5-411:-N6CL_571Ig-YGx_QILI:b-8fx2u7) ([raw file](https://github.com/ethersphere/bee/blob/b1358060cf362a93debdce19d209cd5cf672dd9c/pkg/pushsync/pushsync.go#L411)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

much cleaner, thanks :)
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-07-05 13:51 UTC, notanatol reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3052)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @acud, @aloknerurkar, @istae, @metacertain, and @mrekucci)

___
*[`pkg/pushsync/pushsync.go` line 361 at r7](https://reviewable.io/reviews/ethersphere/bee/3052#-N6D3j3f8MG339gbJ3GB:-N6DcIgq5R8oQl7qOnHv:by7762h) ([raw file](https://github.com/ethersphere/bee/blob/a727d6cc393f121783712b8feaea17398825fcd8/pkg/pushsync/pushsync.go#L361)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

it is not clear what this boolean value means. it would be nice to have named returns here at least for the sake of clarity, or at least adequate comments describing what is being returned
</blockquote></details>

added comment and names
___
*[`pkg/skippeers/skip_peers.go` line 23 at r4](https://reviewable.io/reviews/ethersphere/bee/3052#-N5iycgzIMgZS924T-47-r4-23:-N6DcA_y6RzxUQwagrwU:b6o6g7f) ([raw file](https://github.com/ethersphere/bee/blob/16c7872296331ac27d24e596713ae871c146b050/pkg/skippeers/skip_peers.go#L23)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

Maybe it would be good to have a unit test, to see that returning the appended output does not result in a grow of the field (i.e. repeated calls with different output return the expected output, not resulting in a grow of the slice, consider also mutating the appended content to see that the returned value does not mutate).
</blockquote></details>

I replaced it with an explicit copy-on-read version, pls review


<!-- Sent from Reviewable.io -->

2022-07-06 07:48 UTC, merged