refactor: deprecate gateway mode
ethersphere/bee pull request #3265
Opened 2022-09-09 08:38 UTC by swarmHaseeb

refactor: deprecate gateway mode
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [x] My change requires a documentation update and I have done it
- [x] I have filled out the description and linked the related issues

### Description

Deprecate gateway mode and removing all related code and update documentation
#### Motivation and context (Optional)

Api refactoring 
### Related Issue (Optional)

closes #2972 
### Screenshots (if appropriate):

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3265)

2022-09-09 12:58 UTC, vladopajic commented on packaging/bee.yaml
> -# gateway-mode: false
Comment should be also removed.

2022-09-09 12:58 UTC, vladopajic commented on packaging/docker/env
>  ## disable a set of sensitive features in the api
Comment should be also removed.

2022-09-09 12:58 UTC, vladopajic commented on packaging/homebrew-amd64/bee.yaml
> -# gateway-mode: false
Comment should be also removed.

2022-09-09 12:58 UTC, vladopajic commented on packaging/homebrew-arm64/bee.yaml
> -# gateway-mode: false
Comment should be also removed.

2022-09-09 12:58 UTC, vladopajic commented on packaging/scoop/bee.yaml
> -# gateway-mode: false
Comment should be also removed.

2022-09-11 12:42 UTC, swarmHaseeb reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3265)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @istae, @mrekucci, @umerm-work, and @vladopajic)

___
*[`packaging/docker/env` line 42 at r1](https://reviewable.io/reviews/ethersphere/bee/3265#-NBWOgFAK9Ag1upjPjBR-r1-42:-NBgZfVNDkir4U6JwcAc:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d5fc952d1cf1fd47e8f2dab0f62408e1af10eb4e/packaging/docker/env#L42)):*
<details><summary><i>Previously, vladopajic (Vlado Pajić) wrote…</i></summary><blockquote>

Comment should be also removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-12 07:56 UTC, vladopajic reviewed
LGTM

2022-09-16 13:28 UTC, notanatol approved these changes

2022-09-16 13:38 UTC, vladopajic approved these changes

2022-09-19 07:23 UTC, mrekucci requested changes
The gateway mode is marked as deprecated, yet it is removed from the code. If a feature or API is marked as deprecated, it should work until the next release and then be removed completely. Either mark it as deprecated in the Open API specification and create a subsequent PR (where it will be removed entirely) that will be included in the release following the release in which it was marked as deprecated. Or remove it completely also from the Open API specification.

2022-09-20 09:21 UTC, mrekucci requested changes
Since the HTTP response set has changed, the version of the Open API specification should also change.

2022-09-21 07:35 UTC, mrekucci requested changes
We try to follow the [semver](https://semver.org/) approach, so in this case, there are no bug fixes or incompatible API changes, so the minor version should be incremented.

2022-09-21 07:35 UTC, mrekucci commented on openapi/SwarmDebug.yaml
> +  version: 2.1.1
There has been no change in the debug API, so there is no need to change the version.

2022-09-22 08:19 UTC, istae requested changes

2022-09-22 08:19 UTC, istae commented on pkg/api/router.go
> -		s.gatewayModeForbidEndpointHandler,
Here we remove the gateway forbidden middleware which blocks users from requesting the tags of all uploads, including others'. Has this been thoroughly discussed ?

2022-09-22 08:32 UTC, istae approved these changes

2022-09-22 11:52 UTC, mrekucci approved these changes

2022-09-23 10:48 UTC, merged