fix: add stamps to store after sync
ethersphere/bee pull request #3269
Opened 2022-09-11 10:34 UTC by swarmHaseeb

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [ ] My change requires a documentation update and I have done it
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues

### Description

stamps will be added to store after sync is complete
#### Motivation and context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2022-09-11 10:46 UTC, istae requested changes

2022-09-11 10:46 UTC, istae commented on pkg/postage/service.go
> +func (ps *service) HandleStamps() error {
I would rename to something like SetExpirations

2022-09-11 10:46 UTC, istae commented on pkg/node/node.go
> +	var statusStampsSynced bool
we do not need this var, we can move the `post.HandleStamps()` after line 774 and again after 783 (after the error checks)

2022-09-11 10:48 UTC, istae commented
PR title and commit message should be something like "set stamps expiration field after batch sync completes"

2022-09-11 12:39 UTC, swarmHaseeb reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3269)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @istae and @swarmHaseeb)

___
*[`pkg/node/node.go` line 747 at r1](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAV-r1-747:-NBgYs73B9OkFMsDOFSA:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6c86d90413a3d63c9fa6c38fc12d9db23197cc85/pkg/node/node.go#L747)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

we do not need this var, we can move the `post.HandleStamps()` after line 774 and again after 783 (after the error checks)
</blockquote></details>

Done.
___
*[`pkg/postage/service.go` line 201 at r1](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAY-r1-201:-NBgYuAXCikfkA8Vig6x:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6c86d90413a3d63c9fa6c38fc12d9db23197cc85/pkg/postage/service.go#L201)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

I would rename to something like SetExpirations
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-11 14:13 UTC, istae requested changes

2022-09-11 14:13 UTC, istae commented on pkg/node/node.go
> +	err = post.ExpirySetter()
this would call `ExpirySetter` twice for light nodes, we just need it once

2022-09-11 14:13 UTC, istae commented on pkg/postage/service.go
> +func (ps *service) ExpirySetter() error {
SetExpired is a better name

2022-09-11 14:14 UTC, istae commented
please revise description

2022-09-12 08:24 UTC, swarmHaseeb reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3269)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @istae)

___
*[`pkg/node/node.go` line 788 at r3](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAV-r3-788:-NBknBga2fIlOGbZfHex:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/c25666730ccd929c300d4b4bf1c678f9dbf39384/pkg/node/node.go#L788)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

this would call `ExpirySetter` twice for light nodes, we just need it once
</blockquote></details>

Done.
___
*[`pkg/postage/service.go` line 212 at r3](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAY-r3-212:-NBknCTkC15YBOCKzI0R:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/c25666730ccd929c300d4b4bf1c678f9dbf39384/pkg/postage/service.go#L212)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

SetExpired is a better name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-12 08:54 UTC, istae requested changes

2022-09-12 08:54 UTC, istae commented on pkg/node/node.go
> +	if err != nil {
what error are we checking here? Where is the `post.SetExpired` for full nodes ?

2022-09-12 09:04 UTC, swarmHaseeb reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3269)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @aloknerurkar, @istae, and @mrekucci)

___
*[`pkg/node/node.go` line 788 at r4](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAV-r4-788:-NBkwI5x2WDMA7Is4nmG:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0edfca6e31857c1f23023fb8011fcd9fda29048b/pkg/node/node.go#L788)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

what error are we checking here? Where is the `post.SetExpired` for full nodes ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-12 09:05 UTC, istae approved these changes

2022-09-12 10:03 UTC, aloknerurkar commented on pkg/node/node.go
> +				err = post.SetExpired()
This should be in an else case or we should return in the above if loop

2022-09-12 10:17 UTC, swarmHaseeb reviewed
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3269)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @aloknerurkar, @istae, and @mrekucci)

___
*[`pkg/node/node.go` line 784 at r5](https://reviewable.io/reviews/ethersphere/bee/3269#-NBg6K8emaCVHpc5CXAV-r5-784:-NBlC8XW4kGWzP8BpiXg:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/7786d6da5c57b802356656d883b601976d917c7a/pkg/node/node.go#L784)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

This should be in an else case or we should return in the above if loop
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-12 10:22 UTC, aloknerurkar approved these changes

2022-09-12 12:00 UTC, merged