feat: add consensus time for sampler
ethersphere/bee pull request #3400
Opened 2022-10-07 10:06 UTC by metacertain

Adding a consensus of deterministic time-delimiter for reserve sample inclusion of chunks based on timestamp of postage stamp

2022-10-07 11:21 UTC, notanatol approved these changes

2022-10-07 11:24 UTC, aloknerurkar commented on pkg/storageincentives/agent.go
> +	timeLimiter := timeLimiterBlock.Time
Do we need to convert this to Nanosecs?

2022-10-07 20:52 UTC, mrekucci commented on pkg/storageincentives/agent.go
> +	MaxInt64              = 9223372036854775807
The max int64 is already defined in the `math` package as `math.MaxInt64`. On top of that, the constant isn't used.

2022-10-07 20:52 UTC, mrekucci commented on pkg/storageincentives/agent.go
> +	block, err := a.backend.BlockNumber(context.Background())
Why `context.Background()` is used instead of existing context?

2022-10-10 13:22 UTC, istae requested changes

2022-10-10 13:22 UTC, istae commented on pkg/storageincentives/agent.go
> +	timeLimiterNanoseconds := timeLimiterBlock.Time * 1000000
assuming timeLimiterBlock.Time is in seconds, the following is more clear
`time.Second * (timeLimiterBlock.Time) / time.Nanosecond`

2022-10-10 13:30 UTC, istae approved these changes

2022-10-10 16:20 UTC, merged