feat(staking): add tx hash
ethersphere/bee pull request #3573
Opened 2022-11-22 15:06 UTC by umerm-work

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
The PR adds transaction hash to the staking API.

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)
#3359

2022-11-22 15:09 UTC, istae requested changes

2022-11-22 15:09 UTC, istae commented on pkg/storageincentives/staking/contract.go
> +		return
`return ErrInsufficientFunds`

2022-11-22 17:00 UTC, istae requested changes

2022-11-22 17:00 UTC, istae commented on pkg/storageincentives/staking/contract.go
> +		return
no need to check if error is nil here, simply `return` works

2022-11-22 17:31 UTC, istae requested changes

2022-11-22 17:31 UTC, istae commented on pkg/storageincentives/staking/contract.go
> +	if receipt != nil {
because there are two transactions here, I would log this one on error
and return the next transaction

2022-11-23 13:35 UTC, mrekucci commented on pkg/api/staking.go
> +			logger.Debug("not implemented", "error", err, "txHash", txHash)
It is preferable to log the error as the last one, the same is mentioned below.

2022-11-24 14:04 UTC, vladopajic approved these changes

2022-11-24 14:24 UTC, merged