chore: fix default values
ethersphere/bee pull request #3964
Opened 2023-04-04 14:57 UTC by vladopajic

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
- Fixed token names for mainnet
- default branch of GetByChainID func will return Testnet config - it's unnecessary to recreate it here

2023-04-05 09:00 UTC, mrekucci requested changes

2023-04-05 09:41 UTC, vladopajic commented on pkg/config/chain.go
> +		return Testnet, false
Also, setting different chainID on testnet config is not correct, because that config is certainly not correct.

2023-04-05 09:56 UTC, vladopajic commented on pkg/config/chain.go
> +		return Testnet, false
Possible resolution for default case of `GetByChainID` method:
1) keep changes from this PR
2) revert change from this PR (leave as is, don't do anything)
3) use testnet config with different chain id  (as @mrekucci has suggested)
4) updated usage of `GetByChainID` by early returning if config was not found
5) other?

2023-04-05 10:04 UTC, vladopajic commented on pkg/config/chain.go
> +		return Testnet, false
everyone, please give your inputs to this

2023-04-12 15:11 UTC, mrekucci approved these changes

2023-04-13 22:19 UTC, istae approved these changes

2023-04-14 12:56 UTC, merged