feat(status): add chainstate total amount
ethersphere/bee pull request #4010
Opened 2023-04-14 23:18 UTC by istae

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2023-04-17 09:10 UTC, aloknerurkar commented on pkg/status/status.go
> +	protocolVersion = "1.1.0"
I approved it, but remember to remove this before checking in.

2023-04-19 09:07 UTC, mrekucci requested changes
The relevant OpenAPI specification should also be updated.

2023-04-19 09:14 UTC, mrekucci commented on pkg/status/status.go
> +	protocolVersion = "1.1.0"
Agree with @aloknerurkar the version is mainly for protocol logic change (or protobuf files breaking change).

2023-04-19 10:00 UTC, mrekucci approved these changes

2023-04-19 10:18 UTC, merged