feat: stamper index assignment rule update (#4552)
ethersphere/bee pull request #4556
Opened 2024-01-23 23:48 UTC by acha-bill

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Stamp fixes
#4552 

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2024-01-25 14:33 UTC, istae requested changes

2024-01-25 14:33 UTC, istae commented on pkg/postage/stamper.go
> +		if st.issuer.ImmutableFlag() {
with the recent developments, this immutable check can be removed.
so in all cases, the timestamp of the index should be updated.

2024-01-25 14:34 UTC, notanatol approved these changes

2024-01-31 02:08 UTC, istae approved these changes
thanks!

2024-01-31 05:08 UTC, merged