feat: split input file to chunks with specified redundancy
ethersphere/bee pull request #4600
Opened 2024-02-29 14:19 UTC by acha-bill

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [x] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Split input file to chunks. Refactored the cmd to 2 subcommands
  - `refs`: outputs only list of refs to file: 
   ```
bee split refs --input-file random.txt --output-file output.txt
  ```
 - `chunks` ouptuts chunks to directory:  
 ```
bee split chunks --input-file random.txt --output-dir ./chunks --r-level 4
```

closes #4599

2024-02-29 17:32 UTC, istae commented on cmd/bee/cmd/split.go
> +	writer, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644)
```suggestion
	writer, err := os.WriteFile(...)
```

2024-03-01 11:32 UTC, istae requested changes

2024-03-01 11:32 UTC, istae commented on cmd/bee/cmd/split_test.go
> +	for _, entry := range entries {
what you want to test is, do the split of the file yourself and compare that to what is stored

2024-03-01 13:46 UTC, notanatol approved these changes

2024-03-04 16:05 UTC, istae approved these changes

2024-03-04 16:05 UTC, merged