fix(seg65)
ethersphere/bee pull request #4604
Opened 2024-03-04 12:11 UTC by zelig

2024-03-04 13:59 UTC, notanatol approved these changes

2024-03-13 11:38 UTC, istae approved these changes

2024-03-13 14:52 UTC, istae requested changes
newSpanEncryption and newDataEncryption should be exported functions so that all the pkgs can reuse the same implemention

2024-03-13 22:01 UTC, istae approved these changes

2024-03-15 08:58 UTC, zelig reviewed
its ok

2024-03-15 13:42 UTC, merged