feat: remove auth
ethersphere/bee pull request #4679
Opened 2024-05-17 16:22 UTC by acha-bill

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [x] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Remove authorization and --restricted option.

Part of #4669

2024-05-17 21:47 UTC, janos reviewed
I think that the "bcrypt" cli command https://github.com/ethersphere/bee/blob/remove-auth/cmd/bee/cmd/bcrypt.go#L15 can be removed, as it was created to help generate admin password hash. I cannot find in the repository that anything else uses bcrypt encryption, but please validate that no other tooling is using this command.

2024-05-30 10:00 UTC, martinconic requested changes

2024-05-30 13:12 UTC, acha-bill commented on .github/workflows/beekeeper.yml
> +  BEEKEEPER_BRANCH: "api-merge"
yep. I was waiting for beekeeper to be released.

2024-05-30 13:13 UTC, acha-bill commented on pkg/api/api_test.go
> +	s.MountTechnicalDebug()
yes. All the API parts are always mounted

2024-05-30 13:22 UTC, acha-bill commented on pkg/node/node.go
> +		apiService.MountAPI()
Not really, I wanted to be consistent. technical > debug > api

2024-05-30 14:06 UTC, istae reviewed
Will to a final review once all the CICD tests are passing.

2024-05-31 12:29 UTC, martinconic approved these changes

2024-05-31 14:38 UTC, merged