fix: add stamphash to wantchunks id
ethersphere/bee pull request #4745
Opened 2024-07-31 11:21 UTC by acha-bill

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Add stamphash to `wantChunks` ID

### Related Issue (Optional)
#4738
#4739

2024-07-31 11:42 UTC, istae commented on pkg/pullsync/pullsync.go
> +		wantChunksID := addr.ByteString() + string(stamp.BatchID()) + string(stampHash)
```suggestion
		wantChunkID := addr.ByteString() + string(stamp.BatchID()) + string(stampHash)
```

2024-07-31 11:45 UTC, istae approved these changes

2024-07-31 14:17 UTC, nugaon requested changes
This does not resolve #4739

2024-07-31 19:24 UTC, martinconic approved these changes

2024-08-06 00:05 UTC, acha-bill commented
> This does not resolve #4739

Moved the fix to #4749

2024-08-08 15:35 UTC, nugaon approved these changes

2024-08-09 08:48 UTC, merged