fix(manifest): resolve node persistence after removal
ethersphere/bee pull request #4819
Opened 2024-09-13 06:48 UTC by asabya

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [x] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
This PR fixes https://github.com/ethersphere/bee/issues/4808. Where loading a manifest then removing forks from it would not persist in the next load.

2024-11-03 21:25 UTC, zelig requested changes
very neat find. please simplify by just nil-ing the ref field

2024-11-03 21:25 UTC, zelig commented on pkg/manifest/mantaray/persist.go
> +	if n != nil && n.ref != nil && !bytes.Equal(n.ref, zero32) {
not needed, see above

2024-11-03 21:25 UTC, zelig commented on pkg/manifest/mantaray/node.go
>  	if len(rest) == 0 {
just put here simply a line

```go
     defer func() { n.ref = nil }()
```

2024-11-28 09:30 UTC, gacevicljubisa commented
@asabya this is the [guide](https://www.conventionalcommits.org/en/v1.0.0/) for commit msgs, linter will not allow merge if msgs are not in correct format. Currenltly this [commit](https://github.com/ethersphere/bee/pull/4819/commits/4a8c3c5d994a9d91e69e7680237274667efb0ebf) msg is not in correct format

2025-01-09 09:23 UTC, istae commented
@asabya can you pls fix the commit msg, see https://github.com/ethersphere/bee/actions/runs/11669094347/job/33647232645?pr=4819#step:5:41

2025-01-10 06:16 UTC, asabya commented
> @asabya can you pls fix the commit msg, see https://github.com/ethersphere/bee/actions/runs/11669094347/job/33647232645?pr=4819#step:5:41

fixed

2025-01-14 16:01 UTC, gacevicljubisa approved these changes

2025-02-13 02:33 UTC, acha-bill approved these changes

2025-03-06 00:19 UTC, merged