fix: print batch id in failed to read upload item log
ethersphere/bee pull request #4827
Opened 2024-09-17 12:31 UTC by martinconic

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Fixes issue [4632](https://github.com/ethersphere/bee/issues/4632)

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2024-09-17 16:27 UTC, janos approved these changes

2024-09-18 08:03 UTC, acha-bill requested changes

2024-09-18 08:03 UTC, acha-bill commented on pkg/storer/internal/upload/uploadstore.go
> +		return fmt.Errorf("failed to read uploadItem %s: %w", ui.BatchID, err)
`ui.BatchID` is `[]byte`. Print it as hex

2024-09-18 10:55 UTC, acha-bill approved these changes

2024-09-18 11:15 UTC, merged

2024-09-18 19:24 UTC, ldeffenb commented on pkg/storer/internal/upload/uploadstore.go
> +		return fmt.Errorf("failed to read uploadItem %x: %w", ui.BatchID, err)
Maybe too late now that it has been merged, but the full key to an uploadItem (according to line 563) is the chunk address AND the batchID.  But I didn't check if upstream invokers of `Report()` might add the chunk ID to their logs if this error ever actually occurs.