fix: adapt comment to corresponding used value
ethersphere/bee pull request #4828
Opened 2024-09-17 12:47 UTC by martinconic

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Fixes [4823](https://github.com/ethersphere/bee/issues/4823)

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2024-09-17 16:26 UTC, janos approved these changes

2024-09-18 02:38 UTC, ldeffenb requested changes
Why mention the 250 twice?

2024-09-18 02:38 UTC, ldeffenb commented on pkg/pullsync/pullsync.go
> +	handleRequestsLimitRate         = time.Second / handleMaxChunksPerSecond // handle max 250 chunks per second per peer
Personally, I would have avoided redundancy with something like:
`handle MaxChunksPerSecond per second per peer`

2024-09-18 07:16 UTC, martinconic commented on pkg/pullsync/pullsync.go
> +	handleRequestsLimitRate         = time.Second / handleMaxChunksPerSecond // handle max 250 chunks per second per peer
good point

2024-09-18 08:01 UTC, acha-bill approved these changes

2024-09-18 09:57 UTC, merged

2024-09-18 11:34 UTC, ldeffenb reviewed
Let 'er rip!

2024-09-18 11:34 UTC, ldeffenb commented on pkg/pullsync/pullsync.go
> +	handleRequestsLimitRate         = time.Second / handleMaxChunksPerSecond // handle max `handleMaxChunksPerSecond` chunks per second per peer
I like that much better as it clarifies that the rate is per second per peer (the latter being important) while not being redundant about the actual value.