docs: update bee configs
ethersphere/bee pull request #4911
Opened 2024-11-25 13:44 UTC by acha-bill

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

### Open API Spec Version Changes (if applicable)

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

closes #4806

2024-11-25 15:11 UTC, martinconic requested changes

2024-11-25 15:11 UTC, martinconic commented on packaging/bee.yaml
> +# tracing-service-name: ""
Please check for all duplicates for example `tracing-service-name` is repeating

2024-11-26 15:52 UTC, istae approved these changes

2024-11-28 10:02 UTC, martinconic commented
I think if you want to trigger the other checks you have to change something in the `go` files. @acha-bill

2024-12-09 09:40 UTC, merged